Add `key` to gc data set.
projectnessie/nessie pull request #1031
Opened 2021-04-05 16:02 UTC by rymurr

The `key` is the `Key` or table name and is carried through the GC process to provide more context to the end user.

2021-04-08 08:50 UTC, snazy commented
@rymurr can you merge main?

2021-04-08 09:15 UTC, rymurr commented
> @rymurr can you merge main?

done!

2021-04-08 10:09 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1031)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[versioned/gc/iceberg/src/main/java/org/projectnessie/versioned/gc/AssetKeySerializer.java, line 33 at r1](https://reviewable.io/reviews/projectnessie/nessie/1031#-MXkwfVu9-pV4_xv5Yi4:-MXkwfVu9-pV4_xv5Yi5:bcgjvre) ([raw file](https://github.com/projectnessie/nessie/blob/206a2318f792aabf99d02f0b8eac42969614781e/versioned/gc/iceberg/src/main/java/org/projectnessie/versioned/gc/AssetKeySerializer.java#L33)):*
> ```Java
>  * not be persisted and only used to move around Spark. If it is the ObjectMapper needs to be configured the same way.
>  */
> public class AssetKeySerializer implements Serializer<AssetKey>, Serializable {
> ```

Why this change?
___
*[versioned/gc/iceberg/src/main/java/org/projectnessie/versioned/gc/ValueTypeFilter.java, line 27 at r1](https://reviewable.io/reviews/projectnessie/nessie/1031#-MXkwh8C1AUkW3jtnhsX:-MXkwh8C1AUkW3jtnhsY:bcgjvre) ([raw file](https://github.com/projectnessie/nessie/blob/206a2318f792aabf99d02f0b8eac42969614781e/versioned/gc/iceberg/src/main/java/org/projectnessie/versioned/gc/ValueTypeFilter.java#L27)):*
> ```Java
> import com.google.protobuf.ByteString;
> 
> public class ValueTypeFilter implements FilterFunction<CategorizedValue>, Serializable {
> ```

Why this change?


<!-- Sent from Reviewable.io -->

2021-04-08 10:10 UTC, snazy reviewed
Err - didn't want to "block"/"request changes" (fat finger bug)
Actually the opposite... happy with this one, if @laurentgo is.

2021-04-08 12:22 UTC, rymurr commented
those package-private to public changes should be part of #1032 removed them from this PR

2021-04-15 12:19 UTC, rymurr commented
@snazy and @laurentgo any thoughts on this one?

2021-04-15 12:43 UTC, snazy commented
See [here](https://github.com/projectnessie/nessie/pull/1031#pullrequestreview-631215156) ;)

2021-04-20 12:01 UTC, snazy approved these changes

2021-04-20 12:20 UTC, merged