Don't run CI for markdown file changes
projectnessie/nessie pull request #1606
Opened 2021-07-15 08:42 UTC by nastra

This should properly ignore markdown files in a directories of the repo

2021-07-15 08:44 UTC, rymurr approved these changes

2021-07-15 09:00 UTC, snazy requested changes
That would prevent building the `site/` contents for a pull request.

2021-07-15 09:03 UTC, rymurr commented
> That would prevent building the `site/` contents for a pull request.

good point @snazy

2021-07-15 09:06 UTC, nastra commented
> That would prevent building the `site/` contents for a pull request.

good point

2021-07-19 08:08 UTC, snazy approved these changes

2021-07-21 06:35 UTC, snazy approved these changes

2021-07-21 06:35 UTC, merged