Support stored procedure for Identify expired contents
projectnessie/nessie pull request #3626
Opened 2022-03-16 01:27 UTC by ajantha-bhat

This PR depends on #3421, will be rebased once it is merged.
Currently only top commit maps to this PR changes.

2022-03-24 11:00 UTC, ajantha-bhat commented on gc/gc-base/src/test/java/org/projectnessie/gc/base/AbstractRestGC.java
> +  protected void performGc(
extending and overriding the same test classes with call procedure. Hence changing the access specifier.

2022-03-24 11:02 UTC, ajantha-bhat commented on gc/gc-iceberg/pom.xml
> +    <dependency>
After #3692, this will depend on uber jar and `client.nessie.version`

2022-03-28 15:49 UTC, snazy requested changes
This PR is tackling different changes - please split those into different PRs.

2022-03-28 16:58 UTC, ajantha-bhat commented
> This PR is tackling different changes - please split those into different PRs.

As I mentioned in the PR description, the latest commit is only map to this PR. Rest is from #3421.
Once, It is merged, I an rebase it so that only this PR changes are visible.

2022-03-28 17:01 UTC, ajantha-bhat commented
I will try to split the testcase refactoring and adding base procedure to another PR.

2022-04-04 09:22 UTC, ajantha-bhat commented
> Took out some code to https://github.com/projectnessie/nessie/pull/3814 
 and https://github.com/projectnessie/nessie/pull/3829.

Only top commit maps to this PR changes now.

2022-04-04 11:08 UTC, ajantha-bhat commented on gc/gc-iceberg/src/main/java/org/projectnessie/gc/iceberg/IdentifyExpiredSnapshotsProcedure.java
> +public class IdentifyExpiredSnapshotsProcedure extends BaseGcProcedure {
Detail documentation will be added after both `identify()` and `expire()` call procedure is added. Tracker: https://github.com/projectnessie/nessie/issues/2020

2022-04-04 11:36 UTC, ajantha-bhat commented on gc/gc-iceberg/src/main/java/org/projectnessie/gc/iceberg/IdentifyExpiredSnapshotsProcedure.java
> +  private static final ProcedureParameter[] PARAMETERS =
arguments are same as `GCParams`

2022-04-05 10:20 UTC, closed without merging