tests in nessie-quarkus now can use dynamic ports instead of default port number 19121
projectnessie/nessie pull request #5288
Opened 2022-09-29 10:24 UTC by sagar-agarwal2404

the hardcoded port numbers are been removed from the files and now it uses dynamic ports

2022-09-30 13:09 UTC, sagar-agarwal2404 commented
@ajantha-bhat please review it.

2022-10-03 06:02 UTC, sagar-agarwal2404 commented on servers/quarkus-server/src/main/resources/application.properties
> +quarkus.http.test-port=0
Yeah i forgot to remove that. Now i have removed it. @ajantha-bhat please check.

2022-10-03 06:10 UTC, ajantha-bhat approved these changes

2022-10-03 07:00 UTC, sagar-agarwal2404 commented
> @sagar-agarwal2404: If the PR is linked to an issue. We need to add `Fixes #[issueNumber]` for example Fixes#4015
> 
> And PR description can be simplified to "Use dynamic ports for tests in nessie-quarkus"

is it fine now?

2022-10-04 09:42 UTC, snazy requested changes
This change adds an explicit dependency to a system property that only exists for Quarkus tests to all jax-rs based tests, which should really be avoided.

2022-10-04 09:42 UTC, snazy commented on servers/quarkus-server/src/test/java/org/projectnessie/server/error/TestNessieError.java
> +  static String port = System.getProperty("quarkus.http.test-port");
Nit: `static final` (below as well)

2022-10-10 11:44 UTC, sagar-agarwal2404 commented on servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/AbstractRest.java
> +    String port = System.getProperty("quarkus.http.test-port");
@snazy can you give some hint, how to solve this issue?

2022-10-13 05:14 UTC, XN137 commented
closing in favor of https://github.com/projectnessie/nessie/pull/5352

2022-10-13 05:14 UTC, closed without merging