Mongo load support
projectnessie/nessie pull request #545
Opened 2020-12-10 17:39 UTC by stevelorddremio

2020-12-10 17:47 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @stevelorddremio)

___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 308 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCkorVEembPZAjhm6d:-MOCkorVEembPZAjhm6e:ba0spr6) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L308)):*
> ```Java
>     }
> 
>     final MongoCollection<V> collection = (MongoCollection<V>) getCollection(type);
> ```

Is this cast redundant?
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 347 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCksApBeBiPsWuV_Ih:-MOCksApBeBiPsWuV_Ii:ba0spr6) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L347)):*
> ```Java
>   @Override
>   public <V> V loadSingle(ValueType valueType, Id id) {
>     final MongoCollection<V> collection = (MongoCollection<V>) getCollection(valueType);
> ```

Is this cast redundant?


<!-- Sent from Reviewable.io -->

2020-12-10 19:32 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @stevelorddremio)

___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 249 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD1BYT7OVPVV_8rMHK:-MOD1BYT7OVPVV_8rMHL:bw8mfaw) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L249)):*
> ```
> LoadOps
> ```
I don't think you quite need `loadOps`, or for code clarity, it could be defined as `Collection<LoadOp<?>> loadOps = idLoadOps.values();` (which would limit memory usage)
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 254 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD23tmCPMGXez0lMfx:-MOD23tmCPMGXez0lMfy:b-oix8sg) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L254)):*
> ```Java
>           Multimaps.index(loadOps, l -> collections.get(l.getValueType()));
> 
>       for (MongoCollection<? extends HasId> collection : collectionToOps.keySet()) {
> ```

why partitioning by collection and then by # of items if ultimately all requests are posted in a giant list of subscribers?
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 266 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD2mwf7toTIz6P583f:-MOD2mwf7toTIz6P583g:b-d0j8q2) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L266)):*
> ```Java
>       int opsRemaining = loadOps.size();
>       for (ObservableSubscriber<HasId> subscriber : subscribers) {
>         await(subscriber);
> ```

no timeout...

I'm also not sure I like this model very much as not quite embracing the async model, and am curious what other people think about it. IMHO, I would expect that each element to be processed as received instead of waiting for the all response to be returned and put into a temporary list, to be then processed and copied in the final list...
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 268 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD0lLR8JmZdKpQtUjA:-MOD0lLR8JmZdKpQtUjB:b5qjs6z) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L268)):*
> ```Java
>         await(subscriber);
>         opsRemaining -= subscriber.getReceived().size();
>         for (Object o : subscriber.getReceived()) {
> ```

Why downcasting?
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 280 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD679i8NpRnyEUyRcg:-MOD679i8NpRnyEUyRch:b-1is84s) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L280)):*
> ```Java
>       if (0 != opsRemaining) {
>         throw new ReferenceNotFoundException(
>             String.format("[%d] object(s) missing. \n\nLoad Objects: %s", opsRemaining, loadOps));
> ```

I'm not sure I need how many objects are missing vs which objects are missing tbh...
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 393 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD78sj5qSU0WJ0VZI1:-MOD78sk6pziYb9DvkXY:bgxpuot) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L393)):*
> ```Java
>     } catch (Throwable throwable) {
>       Throwables.throwIfUnchecked(throwable);
>       throw new RuntimeException(throwable);
> ```

shouldn't `ExecutionException` be unwrapped? (I guessed missed in previous patch). Also, I would be inclined to throw `TimeoutException`/`InterruptedException` as-is too (meaning changing `ObservableSubscriber#await()` to a more restricted list of exceptions to be thrown vs the very generic `Throwable`)


<!-- Sent from Reviewable.io -->

2020-12-10 19:32 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @stevelorddremio)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD7xIv-4faM4Nv_Dmk:-MOD7xIv-4faM4Nv_Dml:b-jykp8p) (no related file):*
I'm not seeing unit tests, only conformance tests. I believe we need both

---


<!-- Sent from Reviewable.io -->

2020-12-11 04:37 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 2 files reviewed, 15 unresolved discussions (waiting on @jacques-n, @laurentgo, and @stevelorddremio)

___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 178 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCj9KVOpv7_ePVUYnC-r1-178:-MOF1Mhu-odhVMp09R7a:bqmjwcz) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L178)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

It would be good to have javadoc on why this makes sense.
</blockquote></details>

Added.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 249 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD1BYT7OVPVV_8rMHK:-MODsqdfDN1_xN5emggE:b-b82tvf) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L249)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
> LoadOps
> ```
I don't think you quite need `loadOps`, or for code clarity, it could be defined as `Collection<LoadOp<?>> loadOps = idLoadOps.values();` (which would limit memory usage)
</blockquote></details>

Removed, it had been kept before only to give some visibility of the loadops in the case there is a problem loading items, but it did a poor job of it.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 254 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD23tmCPMGXez0lMfx:-MODENq7DfPAFS-VSZaU:bf1bnwa) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L254)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

why partitioning by collection and then by # of items if ultimately all requests are posted in a giant list of subscribers?
</blockquote></details>

Needs to be partitioned by collection as the finds operation on the collection. Mongo has a document limit of 16MB, and b/c we're using an IN condition to retrieve the relevant documents, the query itself is treated as a document and thus has a size limit and must be partitioned.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 265 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCj9KVOpv7_ePVUYnC-r1-265:-MODnplr2JboFyqbKIa7:baf4lyn) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L265)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

Let's do this as they complete, not in linear order.
</blockquote></details>

Agreed, an echo of the comment Laurent left below.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 266 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD2mwf7toTIz6P583f:-MODFrCB8WItgPWbKZaZ:b-i9vrse) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L266)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

no timeout...

I'm also not sure I like this model very much as not quite embracing the async model, and am curious what other people think about it. IMHO, I would expect that each element to be processed as received instead of waiting for the all response to be returned and put into a temporary list, to be then processed and copied in the final list...
</blockquote></details>

There is a timeout, but it's implicit in the call. Regarding the async nature, that's a fair comment, and I agree.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 268 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD0lLR8JmZdKpQtUjA:-MODnmHUArjLS8Kt-K98:bqxzfns) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L268)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Why downcasting?
</blockquote></details>

Must have been a leftover, it's obsolete.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 280 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD679i8NpRnyEUyRcg:-MOEopGVBpBtxQR79qMt:b-dvp0yj) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L280)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I'm not sure I need how many objects are missing vs which objects are missing tbh...
</blockquote></details>

Reworked this to just output the missing IDs.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 393 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD78sj5qSU0WJ0VZI1:-MODsndPAwRVpVjnn2ni:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L393)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

shouldn't `ExecutionException` be unwrapped? (I guessed missed in previous patch). Also, I would be inclined to throw `TimeoutException`/`InterruptedException` as-is too (meaning changing `ObservableSubscriber#await()` to a more restricted list of exceptions to be thrown vs the very generic `Throwable`)
</blockquote></details>

Done.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 397 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCj9KVOpv7_ePVUYnC-r1-397:-MODptWbDeMKRLNNImpA:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L397)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

Can you coerce here rather than at each call point?
</blockquote></details>

Done.
___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/tests/AbstractTestStore.java, line 86 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCj9KVOpv7_ePVUYnD-r1-86:-MOEpiarCOxVfkvkGwn-:bb6sh2i) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/tests/AbstractTestStore.java#L86)):*
<details><summary><i>Previously, jacques-n (Jacques Nadeau) wrote…</i></summary><blockquote>

let's make sure we have a test that tests pagination.
</blockquote></details>

Ack.
___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/tests/AbstractTestStore.java, line 87 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCj9KVOpv7_ePVUYnD-r1-87:-MOEpeJq4mTETjZ1CLSe:b-nrjlas) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/tests/A [...]

2020-12-14 18:42 UTC, stevelorddremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 3 files reviewed, 15 unresolved discussions (waiting on @jacques-n, @kylep-dremio, and @laurentgo)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD7xIv-4faM4Nv_Dmk:-MOXYIxQ8k4Ef-Hua7US:b-c0lwj6) (no related file):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I'm not seeing unit tests, only conformance tests. I believe we need both
</blockquote></details>

As this PR is one of several on MongoDB, can we defer this to a later PR, but before code is complete? It would help with getting all changes reviewed.

---
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 308 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCkorVEembPZAjhm6d:-MOXY79QEQ8F5BqKc4gC:b-av023g) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L308)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Is this cast redundant?
</blockquote></details>

Yes, removed.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 347 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOCksApBeBiPsWuV_Ih:-MOXYmpB3_Dt5ObVqBsy:b-av023g) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L347)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Is this cast redundant?
</blockquote></details>

Yes, removed.


<!-- Sent from Reviewable.io -->

2020-12-14 19:19 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 3 files reviewed, 13 unresolved discussions (waiting on @jacques-n, @kylep-dremio, @laurentgo, and @stevelorddremio)

___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 254 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD23tmCPMGXez0lMfx:-MOXf2bxBl839ECZtlx1:bqcyv0t) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L254)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Needs to be partitioned by collection as the finds operation on the collection. Mongo has a document limit of 16MB, and b/c we're using an IN condition to retrieve the relevant documents, the query itself is treated as a document and thus has a size limit and must be partitioned.
</blockquote></details>

Yes, I remember figuring it out but forgot to remove my comment (I'm going back and forth in the source code)
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 393 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD78sj5qSU0WJ0VZI1:-MOXg1mgCpeJt0ZVRRp9:b-y177i0) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L393)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it? I don't see any change regarding `TimeoutException`/`InterruptedException`


<!-- Sent from Reviewable.io -->

2020-12-14 19:20 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 3 files reviewed, 13 unresolved discussions (waiting on @jacques-n, @kylep-dremio, @laurentgo, and @stevelorddremio)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD7xIv-4faM4Nv_Dmk:-MOXgUW_Dx0h5l_wxlyS:bkbnoux) (no related file):*
<details><summary><i>Previously, stevelorddremio (Steve Lord) wrote…</i></summary><blockquote>

As this PR is one of several on MongoDB, can we defer this to a later PR, but before code is complete? It would help with getting all changes reviewed.
</blockquote></details>

Sorry, tests are part of the code and should be reviewed too...

---


<!-- Sent from Reviewable.io -->

2020-12-17 17:16 UTC, kylep-dremio commented
This patch has expanded from simply adding load support to changing to use Flux and improve the code in general.

2020-12-17 17:18 UTC, rymurr commented
> This patch has expanded from simply adding load support to changing to use Flux and improve the code in general.

regarding reactive framework: we should make sure it is supported by Quarkus. Otherwise we cant run the native image w/ Mongo.

2020-12-17 17:27 UTC, rymurr commented
More context on my quarkus comment:

* to compile on graalvm quarkus is super aggressive wrt reflection and proxies and other fun java stuff. So if a framework uses a lot of reflection it likely won't compile w/ quarkus.
* quarkus typically makes a shim module for certain libraries to make it work
* https://quarkus.io/guides/getting-started-reactive talks about Flux so probably fine, but something to be aware of

2020-12-17 21:52 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @jacques-n, @kylep-dremio, @laurentgo, and @stevelorddremio)

___
*[pom.xml, line 476 at r3](https://reviewable.io/reviews/projectnessie/nessie/545#-MOgWNXo-CP4CHEELl33:-MOgWNXo-CP4CHEELl34:bbgpbv3) ([raw file](https://github.com/projectnessie/nessie/blob/104ca076466ae28f809347351b5ce9ebb039193f/pom.xml#L476)):*
> ```XML
>       <dependency>
>         <groupId>io.projectreactor</groupId>
>         <artifactId>reactor-core</artifactId>
> ```

there's a bill of materials artifact for this project: https://projectreactor.io/docs/core/release/reference/#_maven_installation
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 309 at r3](https://reviewable.io/reviews/projectnessie/nessie/545#-MOgYfBOBbC6NmELX-GB:-MOgYfBOBbC6NmELX-GC:b-yapbuv) ([raw file](https://github.com/projectnessie/nessie/blob/104ca076466ae28f809347351b5ce9ebb039193f/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L309)):*
> ```Java
>   @VisibleForTesting
>   void resetCollections() {
>     collections.forEach((k, v) -> Mono.from(v.deleteMany(Filters.ne("_id", "s"))).block(timeout));
> ```

Can be done in parallel instead:
```
  Flux.from(collections).flatMap(entry -> entry.getValue().deleteMany(...)).blockLast(timeout);
```
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 210 at r4](https://reviewable.io/reviews/projectnessie/nessie/545#-MOm_zVg3c_sHf8nXUNJ:-MOm_zVhA98zBAPgra1l:byayqzw) ([raw file](https://github.com/projectnessie/nessie/blob/4c876c6d69e1bee8e095b149f8db8c08cc5c5f31/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L210)):*
> ```Java
>         .publishOn(Schedulers.boundedElastic())
>         .flatMap(entry -> Flux.fromStream(
>             Lists.partition(Lists.transform(entry.collectList().block(timeout), LoadOp::getId), LOAD_SIZE).stream()
> ```

I wonder why it is needed to block the operation here (I guess originally for batching)?

Looks like you can use Flux for batching/buffering:
```
  Flux.fromStream(step.getOps())
    .groupBy(op -> collections.get(op.getValueType()))
    .flatMap(entry -> entry.collectList().map(LoadOp::getId).buffer(LOAD_SIZE).map(l -> new CollectionLoadIds(entry.key(), l))))
    .flatMap[...]
```


<!-- Sent from Reviewable.io -->

2020-12-17 22:27 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @jacques-n, @laurentgo, and @stevelorddremio)

___
*[pom.xml, line 476 at r3](https://reviewable.io/reviews/projectnessie/nessie/545#-MOgWNXo-CP4CHEELl33:-MOmnn3OA1H2-JqUvadv:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/104ca076466ae28f809347351b5ce9ebb039193f/pom.xml#L476)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

there's a bill of materials artifact for this project: https://projectreactor.io/docs/core/release/reference/#_maven_installation
</blockquote></details>

Done.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 254 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD23tmCPMGXez0lMfx:-MOd0Jfe7abfANjjpJdf:b-54avio) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L254)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Yes, I remember figuring it out but forgot to remove my comment (I'm going back and forth in the source code)
</blockquote></details>

Ok, thanks.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 393 at r1](https://reviewable.io/reviews/projectnessie/nessie/545#-MOD78sj5qSU0WJ0VZI1:-MOmo1lg1Eljoy41OBRk:bg1qn3h) ([raw file](https://github.com/projectnessie/nessie/blob/e0588f51e0e5d12e6a738fe2781d04a4f7a98fd3/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L393)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is it? I don't see any change regarding `TimeoutException`/`InterruptedException`
</blockquote></details>

As discussed, this is now obsolete (I believe) since we're using Reactor.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 309 at r3](https://reviewable.io/reviews/projectnessie/nessie/545#-MOgYfBOBbC6NmELX-GB:-MOmo5LK1IJY3zlFCDzy:benvu3) ([raw file](https://github.com/projectnessie/nessie/blob/104ca076466ae28f809347351b5ce9ebb039193f/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L309)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Can be done in parallel instead:
```
  Flux.from(collections).flatMap(entry -> entry.getValue().deleteMany(...)).blockLast(timeout);
```
</blockquote></details>

Done, although it should only ever be called from test code, not production code.
___
*[versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 210 at r4](https://reviewable.io/reviews/projectnessie/nessie/545#-MOm_zVg3c_sHf8nXUNJ:-MOmns8t3Xlg4rirv6dC:b-d7cuh2) ([raw file](https://github.com/projectnessie/nessie/blob/4c876c6d69e1bee8e095b149f8db8c08cc5c5f31/versioned/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L210)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I wonder why it is needed to block the operation here (I guess originally for batching)?

Looks like you can use Flux for batching/buffering:
```
  Flux.fromStream(step.getOps())
    .groupBy(op -> collections.get(op.getValueType()))
    .flatMap(entry -> entry.collectList().map(LoadOp::getId).buffer(LOAD_SIZE).map(l -> new CollectionLoadIds(entry.key(), l))))
    .flatMap[...]
```
</blockquote></details>

Done without the collectList as that's actually not necessary. buffer() will do everything we need to partition, thanks!


<!-- Sent from Reviewable.io -->

2020-12-18 22:25 UTC, laurentgo requested changes
> Reviewed 1 of 2 files at r4, 2 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 3 of 7 files reviewed, 9 unresolved discussions (waiting on @jacques-n and @stevelorddremio)

___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 86 at r5](https://reviewable.io/reviews/projectnessie/nessie/545#-MOrvxSC4G-Y8CLY-Xs4:-MOrvxSD6bJJG1dMug5x:b8o9ws) ([raw file](https://github.com/projectnessie/nessie/blob/c8fdce61d2014fee353168ae43d5c5dc3904867c/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L86)):*
> ```Java
>     // Create the mocks necessary to override behaviour.
>     final FindPublisher<InternalRef> mockPublisher = Mockito.mock(FindPublisher.class);
>     final ArgumentCaptor<Subscriber<InternalRef>> subCaptor = ArgumentCaptor.forClass(Subscriber.class);
> ```

It is not recommended to use ArgumentCaptor for stubbing (https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#15). Have you looked at reactor-test module, or maybe simply create a Flux with your values, and mockito to delegate to it (https://javadoc.io/static/org.mockito/mockito-core/3.6.28/org/mockito/AdditionalAnswers.html#delegatesTo-java.lang.Object-)?
___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 107 at r5](https://reviewable.io/reviews/projectnessie/nessie/545#-MOrx2D9C-7BfAhIrO2K:-MOrx2D9C-7BfAhIrO2L:b-agfbmk) ([raw file](https://github.com/projectnessie/nessie/blob/c8fdce61d2014fee353168ae43d5c5dc3904867c/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L107)):*
> ```Java
>     final LoadStep step = createTestLoadStep(objs);
> 
>     // Since the operations are async, start a thread to wait a bit of time before returning the extra entity.
> ```

why waiting? 2seconds is a long time for a test...


<!-- Sent from Reviewable.io -->

2020-12-20 02:26 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 2 of 8 files reviewed, 9 unresolved discussions (waiting on @jacques-n, @laurentgo, and @stevelorddremio)

___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 86 at r5](https://reviewable.io/reviews/projectnessie/nessie/545#-MOrvxSC4G-Y8CLY-Xs4:-MOxxv_ZAUJZmC5oP1OM:b-hvcopq) ([raw file](https://github.com/projectnessie/nessie/blob/c8fdce61d2014fee353168ae43d5c5dc3904867c/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L86)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

It is not recommended to use ArgumentCaptor for stubbing (https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#15). Have you looked at reactor-test module, or maybe simply create a Flux with your values, and mockito to delegate to it (https://javadoc.io/static/org.mockito/mockito-core/3.6.28/org/mockito/AdditionalAnswers.html#delegatesTo-java.lang.Object-)?
</blockquote></details>

Reworked to avoid the captor.
___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 107 at r5](https://reviewable.io/reviews/projectnessie/nessie/545#-MOrx2D9C-7BfAhIrO2K:-MOxnI63CocegjA8G75s:b-55x85g) ([raw file](https://github.com/projectnessie/nessie/blob/c8fdce61d2014fee353168ae43d5c5dc3904867c/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L107)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

why waiting? 2seconds is a long time for a test...
</blockquote></details>

Chosen arbitrarily, reduced to 25ms.


<!-- Sent from Reviewable.io -->

2020-12-21 21:28 UTC, laurentgo requested changes
> Reviewed 1 of 7 files at r5, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @jacques-n, @kylep-dremio, and @stevelorddremio)

___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 107 at r5](https://reviewable.io/reviews/projectnessie/nessie/545#-MOrx2D9C-7BfAhIrO2K:-MP6B65M1ThmcXjhJXyN:b-n1soyg) ([raw file](https://github.com/projectnessie/nessie/blob/c8fdce61d2014fee353168ae43d5c5dc3904867c/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L107)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Chosen arbitrarily, reduced to 25ms.
</blockquote></details>

but is the thread + waiting necessary at all? I'm guessing that the reason is that events are not sent until a subscriber is registered, but couldn't a cold publisher be used so that elements are buffered and replayed when a subscriber is registering?


<!-- Sent from Reviewable.io -->

2020-12-21 21:47 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @jacques-n, @laurentgo, and @stevelorddremio)

___
*[versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 107 at r5](https://reviewable.io/reviews/projectnessie/nessie/545#-MOrx2D9C-7BfAhIrO2K:-MP6GLOEDMBA8XqlSxpb:btn0ox4) ([raw file](https://github.com/projectnessie/nessie/blob/c8fdce61d2014fee353168ae43d5c5dc3904867c/versioned/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L107)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

but is the thread + waiting necessary at all? I'm guessing that the reason is that events are not sent until a subscriber is registered, but couldn't a cold publisher be used so that elements are buffered and replayed when a subscriber is registering?
</blockquote></details>

You're correct - and this can be done via a cold publisher, thanks for the pointer.


<!-- Sent from Reviewable.io -->

2020-12-22 17:10 UTC, laurentgo approved these changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @jacques-n and @stevelorddremio)



<!-- Sent from Reviewable.io -->

2021-01-05 17:09 UTC, laurentgo approved these changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/545)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @jacques-n, @laurentgo, and @stevelorddremio)



<!-- Sent from Reviewable.io -->

2021-01-05 17:10 UTC, merged