Provide human readable error messages for bad REST requests
projectnessie/nessie pull request #612
Opened 2020-12-23 13:36 UTC by snazy

Resteasy's validation kicks in quite early on the server side, before any Nessie code gets called.

For example, if you call `com.dremio.nessie.api.ContentsApi.setContents()` with a `null` value for the `hash` parameter, the caller will get a HTTP/404 with a message like `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "exception" (class com.dremio.nessie.error.NessieError), not marked as ignorable (3 known properties: "serverStackTrace", "status", "message"])`, which is rather not helpful.

The reason is, that Resteasy sends a serialized `org.jboss.resteasy.api.validation.ViolationReport`, which has that `exception` field plus a bunch of lists explaining all the violations. `com.dremio.nessie.client.rest.ResponseCheckFilter.decodeErrorObject()` then fails to deserialize that as a `NessieError`.

The approach of this PR is to rename `NessieError.serverStackTrace` to `NessieError.exception` and add the 4 lists from `ViolationReport` as parameters to the `@JsonCreator`.

With this PR, Nessie users get somewhat helpful error messages like these:
* `Bad Request (HTTP/400): parameter nullParameterQueryGet.hash must not be null`
* `Bad Request (HTTP/400): parameter basicEntity.entity.value must be greater than or equal to 3 (value='1')`
* `Bad Request (HTTP/400): parameter blankParameterQueryGet.hash must not be blank (value='   ')`

The added unit test illustrates a couple of validation errors "directly" against the REST method parameters and "indirectly" in the deserialized entities.

Also adds the `@Valid` annotation to all "complex" parameters of the REST API methods, so the validator can process the deserialized entities.

2020-12-28 10:11 UTC, rymurr requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/612)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @rymurr and @snazy)

___
*[model/src/main/java/com/dremio/nessie/error/ConstraintViolation.java, line 1 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnGcg35uYgrNSQ55z:-MPcnGcg35uYgrNSQ56-:b-sh5nky) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/model/src/main/java/com/dremio/nessie/error/ConstraintViolation.java#L1)):*
> ```Java
> /*
> ```

why not use immutables like the other model objects?
___
*[model/src/main/java/com/dremio/nessie/error/NessieError.java, line 34 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnJzX50IPSeGBueEf:-MPcnJzX50IPSeGBueEg:bhg61sq) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/model/src/main/java/com/dremio/nessie/error/NessieError.java#L34)):*
> ```Java
>   private final String message;
>   private final Status status;
>   private final String exception;
> ```

why the rename? The idea was that its clear the error is coming from the server
___
*[model/src/test/java/com/dremio/nessie/error/NessieErrorTest.java, line 2 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnVVA9Ex50HqzRLl7:-MPcnVVBCb8mxAZjO2mB:bxr2uco) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/model/src/test/java/com/dremio/nessie/error/NessieErrorTest.java#L2)):*
> ```Java
> /*
>  * Copyright (C) 2020 Dremio
> ```

please rename to TestNessieError as per other test classes
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java, line 1 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcndG79njk32ghpATd:-MPcndG79njk32ghpATe:b-qhkh3i) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java#L1)):*
> ```Java
> /*
> ```

Also rename
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java, line 50 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnsZAAsUwpovx315H:-MPcnsZAAsUwpovx315I:b-hjp3dh) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java#L50)):*
> ```Java
>  */
> @QuarkusTest
> class NessieErrorTest {
> ```

From my reading of this class and the related changes this only affects the client side correct? The Quarkus service still sends non-json objects? Sorry if I got the wrong end of the stick but I don't see anywhere that the server changes what is sent. If that is the case the python client and cli will still produce unclear results. The original scope of the work was to change on the server side to ensure all clients receive can parseable json.


<!-- Sent from Reviewable.io -->

2020-12-28 19:53 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/612)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @rymurr)

___
*[model/src/main/java/com/dremio/nessie/error/ConstraintViolation.java, line 1 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnGcg35uYgrNSQ55z:-MPeuPhW9fF-RAxk6GXN:bpewgiu) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/model/src/main/java/com/dremio/nessie/error/ConstraintViolation.java#L1)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

why not use immutables like the other model objects?
</blockquote></details>

this class is gone now
___
*[model/src/main/java/com/dremio/nessie/error/NessieError.java, line 34 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnJzX50IPSeGBueEf:-MPdhCUl1Sxxw9zqCHlu:bvth56w) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/model/src/main/java/com/dremio/nessie/error/NessieError.java#L34)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

why the rename? The idea was that its clear the error is coming from the server
</blockquote></details>

reverted
___
*[model/src/test/java/com/dremio/nessie/error/NessieErrorTest.java, line 2 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnVVA9Ex50HqzRLl7:-MPdhejg77kweIVQOAZy:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/model/src/test/java/com/dremio/nessie/error/NessieErrorTest.java#L2)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

please rename to TestNessieError as per other test classes
</blockquote></details>

done
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java, line 1 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcndG79njk32ghpATd:-MPdhhYkDEgljm8a70Wt:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java#L1)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Also rename
</blockquote></details>

done
___
*[servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java, line 50 at r2](https://reviewable.io/reviews/projectnessie/nessie/612#-MPcnsZAAsUwpovx315H:-MPetLUKB-FLZAc8JJJ3:b8453) ([raw file](https://github.com/projectnessie/nessie/blob/5aaa5d0a8e1985dde7bae24d40db935ed21afa87/servers/quarkus-server/src/test/java/com/dremio/nessie/server/error/NessieErrorTest.java#L50)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

From my reading of this class and the related changes this only affects the client side correct? The Quarkus service still sends non-json objects? Sorry if I got the wrong end of the stick but I don't see anywhere that the server changes what is sent. If that is the case the python client and cli will still produce unclear results. The original scope of the work was to change on the server side to ensure all clients receive can parseable json.
</blockquote></details>

It's now handled by `ResteasyExceptionMapper` - a sibling of `NessieExceptionMapper` - and both need to be there. The first one captures `javax.validation.ValidationException` and the Nessie one `Exception` - those cannot be combined (at least, I haven't found a way to do so w/ `@Alternative`, `@Priority`, etc). Sadly, as soon as one of the ExceptionMappers implements `implements ExceptionMapper<ValidationException>`, the `@Inject ServerConfig serverConfig` no longer works and `serverConfig` stays `null` (could only get the config via `Arc.container()`). 


<!-- Sent from Reviewable.io -->

2020-12-29 09:01 UTC, rymurr requested changes
> Reviewed 2 of 9 files at r1, 1 of 4 files at r2, 4 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/612)* status: 6 of 14 files reviewed, 6 unresolved discussions (waiting on @rymurr and @snazy)

___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java, line 68 at r3](https://reviewable.io/reviews/projectnessie/nessie/612#-MPhf8CB7DDqgPG8JXYr:-MPhf8CB7DDqgPG8JXYs:b-jrxsje) ([raw file](https://github.com/projectnessie/nessie/blob/a495b792f3cf232556a527d1c274fe8809b7a53d/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java#L68)):*
> ```Java
>   }
> 
>   private void doUnwrapException(StringBuffer sb, Throwable t) {
> ```

wouldnt it be better to use `printStackTrace` and get the fuil java formatted stack trace? Easier for downstream logging aggregators to parse and read


<!-- Sent from Reviewable.io -->

2020-12-29 10:36 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/612)* status: 4 of 16 files reviewed, 6 unresolved discussions (waiting on @rymurr)

___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java, line 68 at r3](https://reviewable.io/reviews/projectnessie/nessie/612#-MPhf8CB7DDqgPG8JXYr:-MPi1ayW5cJlbZb9RRct:bxfb5oj) ([raw file](https://github.com/projectnessie/nessie/blob/a495b792f3cf232556a527d1c274fe8809b7a53d/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java#L68)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

wouldnt it be better to use `printStackTrace` and get the fuil java formatted stack trace? Easier for downstream logging aggregators to parse and read
</blockquote></details>

It's already done, depending on `ServerConfig.shouldSendstackTraceToAPIClient()`.


<!-- Sent from Reviewable.io -->

2020-12-29 13:23 UTC, rymurr requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/612)* status: 4 of 16 files reviewed, 6 unresolved discussions (waiting on @rymurr and @snazy)

___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java, line 68 at r3](https://reviewable.io/reviews/projectnessie/nessie/612#-MPhf8CB7DDqgPG8JXYr:-MPieP5uBcYi36hvaaWw:b-5cxqx3) ([raw file](https://github.com/projectnessie/nessie/blob/a495b792f3cf232556a527d1c274fe8809b7a53d/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java#L68)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

It's already done, depending on `ServerConfig.shouldSendstackTraceToAPIClient()`.
</blockquote></details>

not sure what you mean. It looks like you are hand iterating the exception here. Maybe I missed the purpose of this method.


<!-- Sent from Reviewable.io -->

2020-12-29 13:30 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/612)* status: 4 of 16 files reviewed, 6 unresolved discussions (waiting on @rymurr)

___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java, line 68 at r3](https://reviewable.io/reviews/projectnessie/nessie/612#-MPhf8CB7DDqgPG8JXYr:-MPigCX3BmuwL8mAOXCC:b-jgul79) ([raw file](https://github.com/projectnessie/nessie/blob/a495b792f3cf232556a527d1c274fe8809b7a53d/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/ResteasyExceptionMapper.java#L68)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

not sure what you mean. It looks like you are hand iterating the exception here. Maybe I missed the purpose of this method.
</blockquote></details>

Just copied what's in `io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyViolationExceptionMapper#doUnwrapException` to get a similar behavior for that part, even if we do not send server stack traces.


<!-- Sent from Reviewable.io -->

2020-12-29 13:37 UTC, rymurr approved these changes

2020-12-29 14:11 UTC, merged

2020-12-29 14:11 UTC, snazy commented
Thanks for the review!