V2 REST declares wrong response types in OpenAPI spec
projectnessie/nessie pull request #6211
Opened 2023-03-03 14:46 UTC by snazy

A couple of response types in the V2 HttpTreeApi were incorrectly declared in the corresponding `@APIResponse`. Especialy `SingleReferenceResponse` was missing, also a few places where V2 now returns HTTP/200 (assign+delete) with the assigned/deleted reference.

Fixes #6210

2023-03-03 15:58 UTC, adutra requested changes

2023-03-03 17:27 UTC, dimas-b commented on model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java
> +              schema = @Schema(implementation = SingleReferenceResponse.class))
Yes, please update examples :+1:

2023-03-03 17:32 UTC, dimas-b commented on model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java
>                  examples = {@ExampleObject(ref = "iceberg")},
Please update this example too.

2023-03-04 14:09 UTC, dimas-b commented on model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java
> +                @ExampleObject(ref = "singleReferencesResponse"),
Quarkus swagger UI error (in browser): 
```
Resolver error at paths./api/v2/trees/{ref}.get.responses.200.content.application/json.examples.singleReferencesResponse.$ref
Could not resolve reference: Could not resolve pointer: /components/examples/singleReferencesResponse does not exist in document
```

It looks like a typo, it should probably be `singleReferenceResponse` (not plural, as in openapi.yaml).

2023-03-04 14:09 UTC, dimas-b commented on model/src/main/resources/META-INF/openapi.yaml
> +    singleReferencesResponseWithMetadata:
typo? Should this be `singleReferenceResponseWithMetadata` (singlular "reference") as above?

2023-03-04 22:56 UTC, dimas-b approved these changes
LGTM. Thanks @snazy !

2023-03-05 19:20 UTC, adutra approved these changes

2023-03-06 11:03 UTC, merged