Add extraEnv to helm chart
projectnessie/nessie pull request #6698
Opened 2023-04-27 16:02 UTC by c-thiel

Fixes #6670

2023-04-27 16:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectnessie/nessie?pullRequest=6698) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/projectnessie/nessie?pullRequest=6698) before we can accept your contribution.<br/><hr/>**Christian Thiel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectnessie/nessie?pullRequest=6698) it.</sub>

2023-04-27 16:25 UTC, adutra requested changes
Nice addition, I like how it's flexible and applies to other possible use cases as well.

2023-04-27 16:25 UTC, adutra commented on helm/nessie/templates/deployment.yaml
>              {{ list .Values.advancedConfig "" | include "nessie.propsToEnvVars" | nindent 12 }}
1. The `{{- range $k, $v := .Values.advancedConfig }}` section is not needed;
2. I think you should put the `extraEnv` section after `advancedConfig` as the former is even more powerful than the latter, so imho it should go last.

```suggestion

            {{ list .Values.advancedConfig "" | include "nessie.propsToEnvVars" | nindent 12 }}

            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
```

2023-04-27 16:35 UTC, adutra commented on helm/nessie/values.yaml
> +# You can pass here any valid Nessie or Quarkus configuration properties.
```suggestion
# You can pass here any valid EnvVar object:
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#envvar-v1-core
```

2023-04-28 20:25 UTC, snazy commented
@c-thiel can you sign the CLA?

2023-04-29 10:12 UTC, c-thiel commented
I signed the CLA for my Github Account. I did some doc changes unfortunately on my iPad with a wrongly configured author.
Is that still fine for you?
Otherwise I would need to create a new PR.

2023-04-30 13:53 UTC, adutra commented
Maybe you could squash your commits and force-push the squashed commit with your verified GitHub account?

2023-05-03 16:39 UTC, c-thiel commented
Ok, I did some rebase. You need to check again though.

2023-05-03 18:42 UTC, adutra approved these changes

2023-05-04 11:34 UTC, merged