JDBC store implementation
projectnessie/nessie pull request #718
Opened 2021-01-25 17:36 UTC by snazy

Still a draft, but passes all integration tests.

The implementation supports multiple dialects to support different databases. At the moment, only hsqldb is implemented, which is used to run the tests.

The code in this PR is based on #700 and definitely not ready for a review, more a dirty proof-of-concept.

2021-02-02 11:44 UTC, rymurr reviewed
> Reviewed 99 of 99 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 98 of 99 files reviewed, 31 unresolved discussions (waiting on @rymurr and @snazy)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXS4Lh8PKKdcRfbpgl:-MSXS4Lh8PKKdcRfbpgm:bqtqgpa) (no related file):*
In general I think there are a bunch of places that should be using getters or shouldn't be exposing members at all. The number of `+` for string concat should be reduced as well.

Ive run the integration tests for both oss and oracle successfully

---
___
*[clients/deltalake/spark2/pom.xml, line 263 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvYV6AIWm9Wq8E_Bs:-MSTvYV6AIWm9Wq8E_Bt:bke7ijz) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/clients/deltalake/spark2/pom.xml#L263)):*
> ```XML
>             <version>${project.version}</version>
>           </dependency>
>           <dependency><!-- The Quarkus-application doesn't build without this dependency. -->
> ```

why did it build before and why is this being added in `spark2` of `deltalake`?
___
*[servers/lambda/src/main/resources/proxy-config.json, line 2 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvhNf25BJ6EhWc8xn:-MSTvhNf25BJ6EhWc8xo:bsg2lem) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/lambda/src/main/resources/proxy-config.json#L2)):*
> ```JSON
> [
> ]
> ```

some comment on this might be useful?
___
*[servers/quarkus-server/pom.xml, line 155 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvrzFDTHLz3V2-tEm:-MSTvrzFDTHLz3V2-tEn:b3qu8h1) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/pom.xml#L155)):*
> ```XML
>       <artifactId>quarkus-amazon-dynamodb</artifactId>
>     </dependency>
>     <dependency>
> ```

these feel like optional or provided? I guess the same w/ dynamo etc. We are saying the server is always built with all supported backends.
___
*[servers/quarkus-server/src/main/resources/application.properties, line 44 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSU2-ii5b2QqXUbPLf0:-MSU2-ii5b2QqXUbPLf1:bqm0dk0) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/src/main/resources/application.properties#L44)):*
> ```INI
> ## JDBC
> # Catalog used to query the database metadata for missing tables.
> nessie.version.store.jdbc.catalog=
> ```

this may be apparent later but what do the catalog and schema options do?
___
*[versioned/tiered/jdbc/pom.xml, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSX0F2T2DKpdGV_mhpY:-MSX0F2T2DKpdGV_mhpZ:b-5u6nvu) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/pom.xml#L68)):*
> ```XML
>       <artifactId>hsqldb</artifactId>
>       <version>${hsqldb.version}</version>
>       <scope>provided</scope>
> ```

do we want the in memory jdbc drivers to be test only?
___
*[versioned/tiered/jdbc/pom.xml, line 103 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSX0NBlCksF5dbu3yyp:-MSX0NBlCksF5dbu3yyq:b-sfn4zv) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/pom.xml#L103)):*
> ```XML
>       <groupId>io.agroal</groupId>
>       <artifactId>agroal-pool</artifactId>
>     </dependency>
> ```

we had a slack conversation that agroal was only in tests? Has this changed or should this be test scoped?
___
*[versioned/tiered/jdbc/pom.xml, line 166 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSX0s-B40eW-jD617Ty:-MSX0s-B40eW-jD617Tz:b1nt34t) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/pom.xml#L166)):*
> ```XML
>             </goals>
>             <configuration>
>               <outputDirectory>${project.build.directory}/native-libraries</outputDirectory>
> ```

which native libs? I dont see where we are extracting any
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/Conditions.java, line 32 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXDGvo6ZD7HkaXeFwy:-MSXDGvo6ZD7HkaXeFwz:b-1vr37n) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/Conditions.java#L32)):*
> ```Java
> final class Conditions {
>   Map<String, ValueApplicator> applicators = new LinkedHashMap<>();
>   boolean ifNotExists;
> ```

We have a habit of using getters/setters for these things. Even though this is internal I see no reason to deviate
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 49 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXEEDkAbYWLgWeb6XG:-MSXEEDkAbYWLgWeb6XH:b-odz93p) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L49)):*
> ```Java
>  * optional batch-DDL operations or upper/lower-case database object checks.</p>
>  */
> @SuppressWarnings("SameParameterValue")
> ```

does thsi have to be class scoped?
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 74 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXET1a2t44XpH1CxrZ:-MSXET1a2t44XpH1Cxr_:b-crjbxu) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L74)):*
> ```Java
>           return "VARCHAR(1)";
>         case REF_NAME:
>           return "VARCHAR(4100)";
> ```

possible to get a bit of javadoc on how these sizes were chosen?
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 375 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXF0kc-olxs_8FXx_L:-MSXF0kc-olxs_8FXx_M:b-791vqo) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L375)):*
> ```Java
>   }
> 
>   boolean getBool(ResultSet resultSet, String column) throws SQLException {
> ```

nit: prefer `setBoolean`
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 92 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXK6HT7B-lXgRQc2vc:-MSXK6HT7B-lXgRQc2vd:b-czw2uk) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L92)):*
> ```Java
>     DELETE(true, false, true);
> 
>     final boolean delete;
> ```

I don't love this. Is there somethign a bit more elegant than triple boolean?

Also prefer getters
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcEntity.java, line 126 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXMR6-BTIZN8WuL7c5:-MSXMR6-BTIZN8WuL7c6:b-uwz9wi) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcEntity.java#L126)):*
> ```Java
>         // e.g. "tree[0]"
>         if ("tree".equals(rootName)) {
>           return rootName + "_" + position;
> ```

nit :`String.format`
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcEntity.java, line 134 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXM_qc [...]

2021-02-02 17:35 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 57 of 102 files reviewed, 27 unresolved discussions (waiting on @rymurr)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXS4Lh8PKKdcRfbpgl:-MSY_-6V6xe83_VrRl4i:b-dmygeh) (no related file):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

In general I think there are a bunch of places that should be using getters or shouldn't be exposing members at all. The number of `+` for string concat should be reduced as well.

Ive run the integration tests for both oss and oracle successfully
</blockquote></details>

The (complicated) ` + ` things are gone. Glad it worked smoothly

---
___
*[clients/deltalake/spark2/pom.xml, line 263 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvYV6AIWm9Wq8E_Bs:-MSY_9MNE6L2PZVl0kV8:b-dign3w) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/clients/deltalake/spark2/pom.xml#L263)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

why did it build before and why is this being added in `spark2` of `deltalake`?
</blockquote></details>

That's a really good question and I admit I don't have an answer for that. Quarkus want 
___
*[servers/lambda/src/main/resources/proxy-config.json, line 2 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvhNf25BJ6EhWc8xn:-MSYk1ZG8gwpVDbJUOMQ:b-4veqp9) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/lambda/src/main/resources/proxy-config.json#L2)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

some comment on this might be useful?
</blockquote></details>

I'd love to, but JSON doesn't like comments ;)
The files have been added, because those are now required by the Lambda native-image-build (as the build-options are pulled in from `nessie-quarkus`, which adds those)
___
*[servers/quarkus-server/pom.xml, line 155 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvrzFDTHLz3V2-tEm:-MSYnNu97cI9GUBuPFwE:b8wm19y) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/pom.xml#L155)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

these feel like optional or provided? I guess the same w/ dynamo etc. We are saying the server is always built with all supported backends.
</blockquote></details>

Not sure I understand what you're asking for. If we want the server to support all backends, the deps shouldn't be optional, no?
___
*[servers/quarkus-server/src/main/resources/application.properties, line 44 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSU2-ii5b2QqXUbPLf0:-MSYkN3C3C9IdnGd-dhF:bxjdq00) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/src/main/resources/application.properties#L44)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this may be apparent later but what do the catalog and schema options do?
</blockquote></details>

Those are used to query the JDBC database metadata for existing tables to check which ones need to be created.
Schema is also prependend to the table names in SQL statements (if the schema is set).
___
*[versioned/tiered/jdbc/pom.xml, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSX0F2T2DKpdGV_mhpY:-MSYkiuz34fF7L72_4SC:bci2mft) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/pom.xml#L68)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

do we want the in memory jdbc drivers to be test only?
</blockquote></details>

Technically, it doesn't matter much overall. We need to pull those in in the `nessie-quarkus` native-image for tests, so it's a "production" code dependency there. I've slightly updated the dependencies.
___
*[versioned/tiered/jdbc/pom.xml, line 103 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSX0NBlCksF5dbu3yyp:-MSYl0hi5mkj-JFTDnsx:b-9450bd) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/pom.xml#L103)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

we had a slack conversation that agroal was only in tests? Has this changed or should this be test scoped?
</blockquote></details>

That's actually the connection pool used by Quarkus. Technically we don't need it, except for the Oracle-JDBC artifact, because the `OracleDatabaseAdapter` class needs access to `OracleConnection` due to the super proprietary way how Oracle JDBC wants users to pass arrays (and yea: the Oracle docs are just wrong - the standard JDBC `setArray` method unconditionally throws an exception).
___
*[versioned/tiered/jdbc/pom.xml, line 166 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSX0s-B40eW-jD617Ty:-MSYlaot13zIirh-G7gZ:bch8zr4) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/pom.xml#L166)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

which native libs? I dont see where we are extracting any
</blockquote></details>

Oops. copy-parte left-over.
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/Conditions.java, line 32 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXDGvo6ZD7HkaXeFwy:-MSYlfCc62nzswj074Qa:b-fie37o) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/Conditions.java#L32)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

We have a habit of using getters/setters for these things. Even though this is internal I see no reason to deviate
</blockquote></details>

Updates those.
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 49 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXEEDkAbYWLgWeb6XG:-MSYlhjT3JkWo_6e3NQv:b-z200pc) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L49)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

does thsi have to be class scoped?
</blockquote></details>

moved to the methods
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 74 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXET1a2t44XpH1CxrZ:-MSYmr842spQOimUa2j8:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L74)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

possible to get a bit of javadoc on how these sizes were chosen?
</blockquote></details>

Done.
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 375 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXF0kc-olxs_8FXx_L:-MSYlji82ajjG4OwJtAJ:bb7f2mf) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L375)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

nit: prefer `setBoolean`
</blockquote></details>

done
___
*[versioned/tiered/jdbc/src/main/java/com/dr [...]

2021-02-02 17:53 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 57 of 102 files reviewed, 27 unresolved discussions (waiting on @rymurr)

___
*[clients/deltalake/spark2/pom.xml, line 263 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvYV6AIWm9Wq8E_Bs:-MSYrZTP5xaDaNYm-dYy:b-k8kync) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/clients/deltalake/spark2/pom.xml#L263)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

That's a really good question and I admit I don't have an answer for that. Quarkus want 
</blockquote></details>

(con't incomplete response)...

Quarkus wants to index `io.quarkus.test.TestTransaction`, which is in `quarkus-test-common`. I suspect, it gets magically added, because of JDBC stuff being added. I just have no clue, why it actually wants to index that particular class/dependency in a non-test configuration. Is this maybe related to the way how `nessie-apprunner-maven-plugin` works?


<!-- Sent from Reviewable.io -->

2021-02-03 09:27 UTC, rymurr reviewed
> Reviewed 1 of 1 files at r2, 21 of 47 files at r3.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 78 of 103 files reviewed, 28 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/718#-MSbCiCM5EaKDVgE1ZWp:-MSbCiCM5EaKDVgE1ZWq:b-x5pfzn) (no related file):*
Looking good. I would like to take another pass later today but aside from a few minor things I am relatively happy.

---
___
*[clients/deltalake/spark2/pom.xml, line 263 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvYV6AIWm9Wq8E_Bs:-MSaxo2A2LZmbrhjdE1s:bmdtp42) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/clients/deltalake/spark2/pom.xml#L263)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

(con't incomplete response)...

Quarkus wants to index `io.quarkus.test.TestTransaction`, which is in `quarkus-test-common`. I suspect, it gets magically added, because of JDBC stuff being added. I just have no clue, why it actually wants to index that particular class/dependency in a non-test configuration. Is this maybe related to the way how `nessie-apprunner-maven-plugin` works?
</blockquote></details>

It could be the way the app runner interacts w/ newer versions of quarkus or something goofy w/ jdbc dependencies. Either way I don't think we want to add `quarkus-test-common` to our 'official' dependency list
___
*[servers/quarkus-server/pom.xml, line 155 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvrzFDTHLz3V2-tEm:-MSayAiN4Zrl8nQklcQX:b46q2vj) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/pom.xml#L155)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Not sure I understand what you're asking for. If we want the server to support all backends, the deps shouldn't be optional, no?
</blockquote></details>

ah yes, misread. I thought we were in services. However we still don't want `h2` and the fact that we need `hsqldb` only to make integration tests pass should be noted.

On the subject...I am actually wondering if we should skip native integration test for this. I don't want to distribute hsql either as i *really* dont want that to be used. Adding hsql to our external deps and as an option in our docker container *just* to make 1 integration test pass seems excessive. 

I think the choice for backend should be in order:
1) dynamo
2) in memory if testing only
3) jdbc if and only if you are forced on prem
4) jgit if you want to have a laugh

In some ways I don't even want to distribute the jdbc adapter w/ the native image as we want to discourage its use. I dunno, thoughts? @laurentgo, would also be curious to see what you think on this topic.
___
*[servers/quarkus-server/src/main/resources/application.properties, line 44 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSU2-ii5b2QqXUbPLf0:-MSazymy2Q2txfAYYmAP:b-93qw3l) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/src/main/resources/application.properties#L44)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Those are used to query the JDBC database metadata for existing tables to check which ones need to be created.
Schema is also prependend to the table names in SQL statements (if the schema is set).
</blockquote></details>

yup, thanks. Was apparent later...hate the double meaning of schema in jdbc
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcStoreConfig.java, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXVzOI3iOVbF3KX864:-MSb9Omv7yyuRFeRUqZ7:b-njopw2) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcStoreConfig.java#L40)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Similar to #757 I wonder if we need to differentiate between creating and initializing
___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java, line 96 at r3](https://reviewable.io/reviews/projectnessie/nessie/718#-MSb9wonApieIuzoes6t:-MSb9wonApieIuzoes6u:baj6pzz) ([raw file](https://github.com/projectnessie/nessie/blob/bed15289565a66f589c0dc3d888cb7a57b9d73bd/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java#L96)):*
> ```Java
> 
>   @Test
>   void branchCommitOverflow() {
> ```

Thanks for adding this. I can't tell from this how the user will see the error. Will the `SQLError` be caught and transformed into a Nessie error before returning to client or will it show up as a `500` error?
___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcVersionStore.java, line 60 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXXPaX0OIHZfoqQt3c:-MSb05K63jn2S6ENLFA4:b-adjerk) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcVersionStore.java#L60)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Added comments about it - TL;DR JUnit doesn't respect an `@Disabled` on the base test class/method.
The two tests have always been disabled (and never passed AFAIK).
</blockquote></details>

only in dynamo that I am aware. Tests work in other places (jgit/inmemory). Was asking why jdbc cant implement it if the other interfaces can. Now I remember that the test is disabled for all `Store` based impls, not just dynamo. Something to tackle later as its an easy fix (or was for inmemory/jgit)


<!-- Sent from Reviewable.io -->

2021-02-04 10:04 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 36 of 57 files reviewed, 28 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/718#-MSbCiCM5EaKDVgE1ZWp:-MSgUWRzAduC36D7GrzE:bx3gk9n) (no related file):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Looking good. I would like to take another pass later today but aside from a few minor things I am relatively happy.
</blockquote></details>

Since #700 is merged now, I've rebased this onto `main`.

---
___
*[clients/deltalake/spark2/pom.xml, line 263 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvYV6AIWm9Wq8E_Bs:-MSgSalVARIT5Lk1qOyK:beukhuf) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/clients/deltalake/spark2/pom.xml#L263)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

It could be the way the app runner interacts w/ newer versions of quarkus or something goofy w/ jdbc dependencies. Either way I don't think we want to add `quarkus-test-common` to our 'official' dependency list
</blockquote></details>

I've removed the integration-tests for the native-image for now, should be handled in #217 
___
*[servers/quarkus-server/pom.xml, line 155 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvrzFDTHLz3V2-tEm:-MSgSr_UEJBFPvkftLkc:bquekgh) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/pom.xml#L155)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

ah yes, misread. I thought we were in services. However we still don't want `h2` and the fact that we need `hsqldb` only to make integration tests pass should be noted.

On the subject...I am actually wondering if we should skip native integration test for this. I don't want to distribute hsql either as i *really* dont want that to be used. Adding hsql to our external deps and as an option in our docker container *just* to make 1 integration test pass seems excessive. 

I think the choice for backend should be in order:
1) dynamo
2) in memory if testing only
3) jdbc if and only if you are forced on prem
4) jgit if you want to have a laugh

In some ways I don't even want to distribute the jdbc adapter w/ the native image as we want to discourage its use. I dunno, thoughts? @laurentgo, would also be curious to see what you think on this topic.
</blockquote></details>

Right. I've removed the integration-tests for the native-image for now, should be handled in #217 

hsqldb should definitely not be in any distribution.

JDBC in the lambda-image is probably wrong, because setting up the connection-pool and getting the connections initialized (some drivers do some expensive initialization) might potentially take too long.
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcStoreConfig.java, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXVzOI3iOVbF3KX864:-MSgTMQE5Oh1qRnziIED:b-2z6faj) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcStoreConfig.java#L40)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Similar to #757 I wonder if we need to differentiate between creating and initializing
</blockquote></details>

It makes most sense in tests, because setting up the tables takes quite long, but (re-)adding the mandatory L1+L2+L3 is necessary for many test cases.
I've removed the new setting from the quarkus configuration though, but left the "split config" in the "internal" config interface.
___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java, line 96 at r3](https://reviewable.io/reviews/projectnessie/nessie/718#-MSb9wonApieIuzoes6t:-MSgTvfE8zgjRy8dhLw9:blsij2b) ([raw file](https://github.com/projectnessie/nessie/blob/bed15289565a66f589c0dc3d888cb7a57b9d73bd/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java#L96)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Thanks for adding this. I can't tell from this how the user will see the error. Will the `SQLError` be caught and transformed into a Nessie error before returning to client or will it show up as a `500` error?
</blockquote></details>

Generally, it depends on what a store implementation actually throws. But it's never a `SQLError`. It's an `IllegalArgumentException` or a `StoreOperationException` wrapping an `IllegalArgumentException`. In both cases, this should result in a `HTTP/500`, which is actually correct IMO, because it is a server-side error (or incomplete implementation).
___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcVersionStore.java, line 60 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSXXPaX0OIHZfoqQt3c:-MSgUKD63T4iLeR6Zy7x:b2o4z14) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcVersionStore.java#L60)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

only in dynamo that I am aware. Tests work in other places (jgit/inmemory). Was asking why jdbc cant implement it if the other interfaces can. Now I remember that the test is disabled for all `Store` based impls, not just dynamo. Something to tackle later as its an easy fix (or was for inmemory/jgit)
</blockquote></details>

It's something in the `TieredVersionStore` if I'm not wrong.


<!-- Sent from Reviewable.io -->

2021-02-04 10:14 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 35 of 57 files reviewed, 28 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java, line 96 at r3](https://reviewable.io/reviews/projectnessie/nessie/718#-MSb9wonApieIuzoes6t:-MSgWQjp48PCxFGZ-8QD:b-we2y7f) ([raw file](https://github.com/projectnessie/nessie/blob/bed15289565a66f589c0dc3d888cb7a57b9d73bd/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java#L96)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Generally, it depends on what a store implementation actually throws. But it's never a `SQLError`. It's an `IllegalArgumentException` or a `StoreOperationException` wrapping an `IllegalArgumentException`. In both cases, this should result in a `HTTP/500`, which is actually correct IMO, because it is a server-side error (or incomplete implementation).
</blockquote></details>

It seems like `com.dremio.nessie.versioned.impl.TieredVersionStore#commit` needs some changes to be aware that a store implementation cannot add any more branch-commits. I don't want to add an explicit read-before-write before the call to `com.dremio.nessie.versioned.store.Store#update`. It might be okay to maybe throw some new `StoreException` from `update` and if that's caught, `commit` runs the `com.dremio.nessie.versioned.impl.InternalBranch.UpdateState#ensureAvailable` and retries  (up to N times). WDYT?


<!-- Sent from Reviewable.io -->

2021-02-04 10:15 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 35 of 57 files reviewed, 28 unresolved discussions (waiting on @jacques-n, @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java, line 96 at r3](https://reviewable.io/reviews/projectnessie/nessie/718#-MSb9wonApieIuzoes6t:-MSgX_3H7fflNRx9BHHj:bez9ogg) ([raw file](https://github.com/projectnessie/nessie/blob/bed15289565a66f589c0dc3d888cb7a57b9d73bd/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java#L96)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

It seems like `com.dremio.nessie.versioned.impl.TieredVersionStore#commit` needs some changes to be aware that a store implementation cannot add any more branch-commits. I don't want to add an explicit read-before-write before the call to `com.dremio.nessie.versioned.store.Store#update`. It might be okay to maybe throw some new `StoreException` from `update` and if that's caught, `commit` runs the `com.dremio.nessie.versioned.impl.InternalBranch.UpdateState#ensureAvailable` and retries  (up to N times). WDYT?
</blockquote></details>

/cc @jacques-n WDYT ^ ?


<!-- Sent from Reviewable.io -->

2021-02-04 12:19 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 33 of 55 files reviewed, 28 unresolved discussions (waiting on @jacques-n, @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java, line 96 at r3](https://reviewable.io/reviews/projectnessie/nessie/718#-MSb9wonApieIuzoes6t:-MSgyBXR3x_vZf22wutm:bgdo8uw) ([raw file](https://github.com/projectnessie/nessie/blob/bed15289565a66f589c0dc3d888cb7a57b9d73bd/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java#L96)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

/cc @jacques-n WDYT ^ ?
</blockquote></details>

It might be necessary that in such an overflow (or better: near-to-overflow) situation, the `ensureAvailable` runs synchronously. Otherwise we might run into a situation that an `ensureAvailable` can practically never properly succeed for branches that have a high commit frequency.

Maybe worth to think about such scenarios in a separate issue?


<!-- Sent from Reviewable.io -->

2021-02-08 11:56 UTC, rymurr reviewed
> Reviewed 19 of 99 files at r1, 1 of 1 files at r2, 25 of 47 files at r3, 20 of 37 files at r4.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 51 of 55 files reviewed, 32 unresolved discussions (waiting on @jacques-n, @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 475 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0MT3A9lWt3DAjrqK1:-MT0MT3A9lWt3DAjrqK2:b58evmv) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L475)):*
> ```Java
>    * @return parsed {@link Key}
>    */
>   static Key fromFlattened(String flattened) {
> ```

is there any utils that already do this? Seems like there is a key serializer at least but im surprised not for other objects like deltas too
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 103 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0MlqlBBPbdjm2hDbZ:-MT0MlqlBBPbdjm2hDb_:b-p1dtsv) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L103)):*
> ```Java
>     }
> 
>     boolean isDelete() {
> ```

nit: maybe a bit more description in what these operations actually are? `isDeleteMustSucceed` is a great example
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 145 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0OKVfEJgI3t1EJd-L:-MT0OKVfEJgI3t1EJd-M:bke68ea) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L145)):*
> ```Java
>             JdbcEntity.ID);
>         ResultSet rs = resources.query(sql, checkStmt -> getDatabaseAdapter().setId(checkStmt, 1, id));
>         throw SQLError.call(rs::next)
> ```

this looks strange to my eye. Does this mean the if block always throws? What is the poitn of the query if we know its goign to throw?
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 162 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0Oc7S7sfX555-3wF0:-MT0Oc7S7sfX555-3wF1:b-wdlptc) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L162)):*
> ```Java
>    */
>   void conditionValue(UpdateContext updateContext, Conditions conditions, ExpressionPath path, Entity value) {
>     conditions.add(
> ```

nit: i feel like having a `doConditionValue` or something which is `protected` and this delegates to is easier to read than package-private and override-able. 
___
*[versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java, line 96 at r3](https://reviewable.io/reviews/projectnessie/nessie/718#-MSb9wonApieIuzoes6t:-MT0SDGC04deZGrzk2e9:bqvfz0a) ([raw file](https://github.com/projectnessie/nessie/blob/bed15289565a66f589c0dc3d888cb7a57b9d73bd/versioned/tiered/jdbc/src/test/java/com/dremio/nessie/versioned/store/jdbc/ITJdbcStore.java#L96)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

It might be necessary that in such an overflow (or better: near-to-overflow) situation, the `ensureAvailable` runs synchronously. Otherwise we might run into a situation that an `ensureAvailable` can practically never properly succeed for branches that have a high commit frequency.

Maybe worth to think about such scenarios in a separate issue?
</blockquote></details>

+1 for separate issue and +1 for 500 error

I think the perf test will throw up a few things around this so it would be good to collect more info before doing anything


<!-- Sent from Reviewable.io -->

2021-02-08 12:23 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 51 of 55 files reviewed, 32 unresolved discussions (waiting on @jacques-n, @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java, line 475 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0MT3A9lWt3DAjrqK1:-MT0WB72-lKKo_h9mxpI:bmcr1xu) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/DatabaseAdapter.java#L475)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

is there any utils that already do this? Seems like there is a key serializer at least but im surprised not for other objects like deltas too
</blockquote></details>

Not really. I wanted to have that functionality with proper escaping and parsing here (and rather private for the jdbc-stuff, because if affects the "serialization").
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 103 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0MlqlBBPbdjm2hDbZ:-MT0aFKR5GlIN01VFi04:b-7tfmjp) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L103)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

nit: maybe a bit more description in what these operations actually are? `isDeleteMustSucceed` is a great example
</blockquote></details>

added
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 145 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0OKVfEJgI3t1EJd-L:-MT0WU--C2NGToqU6Sh4:b97d8e9) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L145)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this looks strange to my eye. Does this mean the if block always throws? What is the poitn of the query if we know its goign to throw?
</blockquote></details>

Yup.  That `SQLError.call` just wraps the `ResultSet.next()`
```
        throw SQLError.call(rs::next)
            ? new ConditionFailedException(conditions.toString())
            : new NotFoundException(conditions.toString());
```
___
*[versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java, line 162 at r4](https://reviewable.io/reviews/projectnessie/nessie/718#-MT0Oc7S7sfX555-3wF0:-MT0XN-U2H4cEXAsAc0j:b-tqye6c) ([raw file](https://github.com/projectnessie/nessie/blob/0560fdd35d9506677a6edee6f87813ed333feb01/versioned/tiered/jdbc/src/main/java/com/dremio/nessie/versioned/store/jdbc/JdbcBaseValue.java#L162)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

nit: i feel like having a `doConditionValue` or something which is `protected` and this delegates to is easier to read than package-private and override-able. 
</blockquote></details>

The "problem" with adapting the Dynamo-ish data-model to JDBC is that some properties are mapped as a JDBC array and some are mapped to a bunch of columns (L1.children, Ref.Branch.children, Ref.Branch.commits). So it was easier to put the logic that can differ the specialized property-handling per value-type into the per-value-type `Jdbc*` classes. 


<!-- Sent from Reviewable.io -->

2021-02-09 06:54 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 50 of 55 files reviewed, 42 unresolved discussions (waiting on @jacques-n, @rymurr, and @snazy)

___
*[NOTICE, line 18 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4SD3j6H0SrPkB8iGz:-MT4SD3k-nCfR7opyMwQ:b-x7x5l9) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/NOTICE#L18)):*
> ```
> =============================================
> 
> http://www.h2database.com/html/license.html
> ```

https:// ?
___
*[pom.xml, line 139 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4SjWr21lO4py9FZtx:-MT4SjWr21lO4py9FZty:b-3161v4) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/pom.xml#L139)):*
> ```XML
>     <junit.version>5.7.0</junit.version>
>     <logback.version>1.2.3</logback.version>
>     <oraclejdbc.version>21.1.0.0</oraclejdbc.version>
> ```

Considering Oracle is not a freely available product, I'm not sure it should be included at this point
___
*[servers/quarkus-server/pom.xml, line 155 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvrzFDTHLz3V2-tEm:-MT4T4zk0HWxsQqiFzzP:b-i7g7ga) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/pom.xml#L155)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Right. I've removed the integration-tests for the native-image for now, should be handled in #217 

hsqldb should definitely not be in any distribution.

JDBC in the lambda-image is probably wrong, because setting up the connection-pool and getting the connections initialized (some drivers do some expensive initialization) might potentially take too long.
</blockquote></details>

In general, our native image generation is not optimal. If we were to follow quarkus practice, configuration should happen at build time, and only one backend should be included...
___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/config/ApplicationConfig.java, line 54 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4TLMV2Vek0O4Nv0k_:-MT4TLMV2Vek0O4Nv0ka:bjh6d6t) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/java/com/dremio/nessie/server/config/ApplicationConfig.java#L54)):*
> ```Java
>                            VersionStoreJGitConfig versionStoreJGitConfig,
>                            VersionStoreDynamoConfig versionStoreDynamoConfig,
>                            VersionStoreJdbcConfig versionStoreJdbcConfig) {
> ```

This clearly doesn't scale...
___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/DatabaseAdapterFactory.java, line 33 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4TSL-49Stvr-3QAiy:-MT4TSL-49Stvr-3QAiz:bodz6x9) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/DatabaseAdapterFactory.java#L33)):*
> ```Java
>  * {@link javax.enterprise.inject.Alternative @Alternative}.
>  */
> @Singleton
> ```

I've been struggling between `@ApplicationScoped` and `@Singleton`. I think we should have been using the former instead of the latter in most cases
___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/VersionStoreFactory.java, line 73 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4U4CH8F1qHhlF9Ynk:-MT4U4CH8F1qHhlF9Ynl:b-qquynk) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/VersionStoreFactory.java#L73)):*
> ```Java
> 
>   @Inject
>   Instance<DataSource> dataSource;
> ```

adding it as fields to the factory seems wrong
___
*[servers/quarkus-server/src/main/resources/application.properties, line 53 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4UMRg428g_-n9BMGl:-MT4UMRg428g_-n9BMGm:bvcyzag) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/resources/application.properties#L53)):*
> ```INI
> # Log the DDL statements to create the tables for Nessie. This just logs the statements
> # independent of the current state of the database objects.
> nessie.version.store.jdbc.logCreateDDL=false
> ```

why not using a logger for that? maybe a lower level or a different logger?

(style) we have been using kebab-case for other properties, let's not mix things and stay consistent?
___
*[servers/quarkus-server/src/main/resources/application.properties, line 56 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4UrNbE56BSLC8fKhH:-MT4UrNbE56BSLC8fKhI:b-d1omc4) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/resources/application.properties#L56)):*
> ```INI
> # The prefix for the Nessie tables.
> nessie.version.store.jdbc.table-prefix=nessie_
> # The type of database being used. Options are: H2, Cockroach, PostgresQL.
> ```

Maybe it should be lower case so that people do not have to figure out the correct capitalization?
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoBaseValue.java, line 61 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4VQhCD7mCiiGkWZmf:-MT4VQhCD7mCiiGkWZmg:b-lk0ao8) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoBaseValue.java#L61)):*
> ```Java
>    * Adds an {@link AttributeValue} that consists of a list of {@link Id}s.
>    */
>   C addIdList43(String key, Stream<Id> ids) {
> ```

what this method is for?
___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoVersionStore.java, line 53 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4Va3X-mLAIv4Wko3q:-MT4Va3X-mLAIv4Wko3r:b2qjer8) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoVersionStore.java#L53)):*
> ```Java
>   }
> 
>   // Need to repeat the @Disabled here, because JUnit fails to respect the @Disabled on the base method.
> ```

is it still true if the base method is not overriden?
___
*[versioned/tiered/jdbc/pom.xml, line 67 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4VmhBDEhrJBABP0hN:-MT4VmhBDEhrJBABP0hO:b-sk9qbc) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/versioned/tiered/jdbc/pom.xml#L67)):*
> ```XML
>       <groupId>org.postgresql</groupId>
>       <artifactId>postgresql</artifactId>
>       <scope>provided</scope>
> ```

do we have code actually depending on postgres? maybe scope should be `runtime` and the dependency should be flagged as `optional` (or should be added as a test dependency)


<!-- Sent from Reviewable.io -->

2021-02-09 10:43 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/718)* status: 50 of 55 files reviewed, 42 unresolved discussions (waiting on @jacques-n, @laurentgo, @rymurr, and @snazy)

___
*[NOTICE, line 18 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4SD3j6H0SrPkB8iGz:-MT5MudgBxacC_AgKSV4:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/NOTICE#L18)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

https:// ?
</blockquote></details>

Done.
___
*[pom.xml, line 139 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4SjWr21lO4py9FZtx:-MT5Mv__2jsCqtMOa6OO:b-cb6og5) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/pom.xml#L139)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Considering Oracle is not a freely available product, I'm not sure it should be included at this point
</blockquote></details>

"Disabled" the `nessie-jdbc-oracle`via a Maven profile, so it's not built by default.
___
*[servers/quarkus-server/pom.xml, line 155 at r1](https://reviewable.io/reviews/projectnessie/nessie/718#-MSTvrzFDTHLz3V2-tEm:-MT5N4koAq3_7vqmJYZC:btr34gr) ([raw file](https://github.com/projectnessie/nessie/blob/0a3e19cdc91f6279bc931251946bc4844c0eb6d6/servers/quarkus-server/pom.xml#L155)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

In general, our native image generation is not optimal. If we were to follow quarkus practice, configuration should happen at build time, and only one backend should be included...
</blockquote></details>

Opened #786 to address this.
___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/config/ApplicationConfig.java, line 54 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4TLMV2Vek0O4Nv0k_:-MT5N7hq7cmtfiv_ef37:b-12rv8x) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/java/com/dremio/nessie/server/config/ApplicationConfig.java#L54)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

This clearly doesn't scale...
</blockquote></details>

Opened #786 to address this.
___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/DatabaseAdapterFactory.java, line 33 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4TSL-49Stvr-3QAiy:-MT5N9jJBwN76ghbT9gx:byilf4p) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/DatabaseAdapterFactory.java#L33)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I've been struggling between `@ApplicationScoped` and `@Singleton`. I think we should have been using the former instead of the latter in most cases
</blockquote></details>

Mentioned this in #786 
___
*[servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/VersionStoreFactory.java, line 73 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4U4CH8F1qHhlF9Ynk:-MT5NEQX50kTd2XAGnys:bm97j2y) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/java/com/dremio/nessie/server/providers/VersionStoreFactory.java#L73)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

adding it as fields to the factory seems wrong
</blockquote></details>

Refactored to method params
___
*[servers/quarkus-server/src/main/resources/application.properties, line 53 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4UMRg428g_-n9BMGl:-MT5NHvn2XZd3Ajr5Zxf:b-pdypgh) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/resources/application.properties#L53)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

why not using a logger for that? maybe a lower level or a different logger?

(style) we have been using kebab-case for other properties, let's not mix things and stay consistent?
</blockquote></details>

Changed to logger. However, the existing implementation for `table-prefix` was using camel-case (-> `tablePrefix`) before.
___
*[servers/quarkus-server/src/main/resources/application.properties, line 56 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4UrNbE56BSLC8fKhH:-MT5NTEbB8sLZkXl44Wj:bre7pjk) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/servers/quarkus-server/src/main/resources/application.properties#L56)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Maybe it should be lower case so that people do not have to figure out the correct capitalization?
</blockquote></details>

Made it case insensitive
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoBaseValue.java, line 61 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4VQhCD7mCiiGkWZmf:-MT5NW5A6kr7W-nx3seF:bkjz70b) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoBaseValue.java#L61)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

what this method is for?
</blockquote></details>

Added some notes to the code. It asserts on the number of L1 children.
___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoVersionStore.java, line 53 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4Va3X-mLAIv4Wko3q:-MT5NcF92XTo2SSy0pPX:bhlnuyf) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoVersionStore.java#L53)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is it still true if the base method is not overriden?
</blockquote></details>

Sadly you have to override it to disable it.
___
*[versioned/tiered/jdbc/pom.xml, line 67 at r5](https://reviewable.io/reviews/projectnessie/nessie/718#-MT4VmhBDEhrJBABP0hN:-MT5Njbh84jznULKLFak:b54j6ln) ([raw file](https://github.com/projectnessie/nessie/blob/e057bbe8e83f627224330b97c46830096809b3a6/versioned/tiered/jdbc/pom.xml#L67)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

do we have code actually depending on postgres? maybe scope should be `runtime` and the dependency should be flagged as `optional` (or should be added as a test dependency)
</blockquote></details>

Made it a `test` dep


<!-- Sent from Reviewable.io -->

2021-02-16 12:19 UTC, snazy commented
Converted the PR back to "draft". There are two reasons for that:
* I've been lazy with rebasing this PR
* The limitation of 15 commits per branch can likely be exceeded, so it's likely that a Nessie server returns a bunch errors back to the client, without a "guard" that protects the store implementation from that many commits per branch.

2021-07-22 11:21 UTC, snazy commented
Closing in favor of #1638

2021-07-22 11:21 UTC, closed without merging