Ability to update the repository description
projectnessie/nessie pull request #7376
Opened 2023-08-16 14:55 UTC by adutra

Note: the update repo functionality is implemented in the old model at adapter level, although, it seems unused. This PR brings the same functionality to the new model.

2023-08-16 17:09 UTC, dimas-b reviewed
Changed LGTM, but it does not look like the new functionality can be accessed. Do you mean to have another PR to expose it somewhere?

2023-08-16 17:11 UTC, dimas-b commented
Would it make sense to add a description update command to `quarkus-cli`?

2023-08-16 17:56 UTC, adutra commented
> Changes LGTM, but it does not look like the new functionality can be accessed. Do you mean to have another PR to expose it somewhere?

Exactly, the idea is to use this functionality in the importer, in order to "mark" the repository as fully imported. I have a draft already: #7380 .

2023-08-16 17:58 UTC, adutra commented
> Would it make sense to add a description update command to `quarkus-cli`?

At this point, that is not required as the only update to the repo description will happen internally inside the importer. We can always add that later though.

2023-08-16 18:39 UTC, dimas-b commented on versioned/storage/common/src/main/java/org/projectnessie/versioned/storage/common/logic/RepositoryLogicImpl.java
> +              Reference reference = Objects.requireNonNull(persist.fetchReference(REF_REPO.name()));
We should probably fix the javadoc of `REF_REPO`, which currently says `Internal reference with always exactly one commit ...`

2023-08-17 05:50 UTC, snazy requested changes

2023-08-17 05:50 UTC, snazy commented on versioned/storage/common/src/main/java/org/projectnessie/versioned/storage/common/logic/RepositoryLogicImpl.java
> +          commitAdd(KEY_REPO_DESCRIPTION, 0, requireNonNull(string.id()), null, UUID.randomUUID()));
This change will only work for new repositories, but existing repositories do not have a content-ID for the repo-description. The update-logic does not work without a content-ID.

I'd prefer to leave the content-ID as `null`. (There's no need for a CID here)

I know that the repo-config stuff uses a CID, see comment in SLImpl

2023-08-17 05:50 UTC, snazy commented on versioned/storage/common/src/main/java/org/projectnessie/versioned/storage/common/logic/StringLogicImpl.java
> +    if (existingContentId == null) {
This makes updating repo-descriptions of already existing repos impossible (those have no CID for repo-description).

Mabe replacing the `if` with a simple `else` helps here.

Should also have some comment to explain the logic wrt repo-desc + repo-config

2023-08-17 08:36 UTC, adutra commented on versioned/storage/common/src/main/java/org/projectnessie/versioned/storage/common/logic/RepositoryLogicImpl.java
> +    // prevent modification of read-only attributes
This came to my mind after @dimas-b suggestion to introduce an option in quarkus-cli to allow end users to modify the repo description. If we ever do that later, I think we'd need a safety net like this one.

2023-08-17 10:41 UTC, snazy commented on versioned/storage/common-tests/src/main/java/org/projectnessie/versioned/storage/commontests/AbstractRepositoryLogicTests.java
> +            .defaultBranchName("main2")
Heh, exactly this one might be updated. Let's remove "defaultBranchName" from that check.
I'm not sure whether there'll ever be a command to update arbitrary information - rather per attribute.

2023-08-17 10:41 UTC, snazy commented on versioned/storage/common-tests/src/main/java/org/projectnessie/versioned/storage/commontests/AbstractRepositoryLogicTests.java
>              .oldestPossibleCommitTime(Instant.ofEpochSecond(12345))
This and the below setting are actually read-only attributes.

2023-08-17 11:43 UTC, snazy approved these changes

2023-08-17 12:10 UTC, merged