Add ConditionExpression and UpdateExpression visitors
projectnessie/nessie pull request #741
Opened 2021-01-29 23:33 UTC by stevelorddremio

Allow non DynamoDB stores to implement alternate ConditionExpression functionality. This is required for MongoDB and RocksDB backing stores.

2021-02-01 14:44 UTC, rymurr requested changes

2021-02-01 14:44 UTC, rymurr commented on versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java
> +    assertEquals(" SET p0 = :v0, p1 = list_append(p1, :v1)", e0p.toUpdateExpressionString());
Why are we removing `if_not_exists` for the dynamo tests? I believe this was required by dynamo under certain circumstances.

2021-02-01 17:41 UTC, stevelorddremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/741)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @rymurr)

___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java, line 122 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSFUfcKDzycROUqN8fF-r1-122:-MSTfV5U5k58ASlcPP7i:boz2jmj) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java#L122)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Why are we removing `if_not_exists` for the dynamo tests? I believe this was required by dynamo under certain circumstances.
</blockquote></details>

It comes from a conversation on nessie-public 12/21/2020
Jacques Nadeau 1:58 PM
It looks like you're referring to the static SetClause.ifNotExists method. If we're not using it anywhere, yes, makes sense to remove.

I did a quick search and can't find it being used. It might have been used in putIfAbsent.


<!-- Sent from Reviewable.io -->

2021-02-01 17:47 UTC, rymurr commented
got it, thanks for the context

2021-02-02 06:13 UTC, laurentgo requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/741)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @rymurr and @stevelorddremio)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWMnMZ3BgFzQLT4YlJ:-MSWMnMZ3BgFzQLT4YlK:b-54vy6a) (no related file):*
Could some unit tests be added to check and also provide some examples on how code can be used?

---
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ConditionExpressionVisitor.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWMJzmDt3lBpjiRPxM:-MSWMJzmDt3lBpjiRPxN:b-h3ag59) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ConditionExpressionVisitor.java#L28)):*
> ```Java
>    * Visitors should call an accept method on ConditionExpression then this callback method is called.
>    */
>   T visit(ConditionExpression conditionExpression);
> ```

I'm not sure I see the point of visiting a `ConditionExpression` if there's no branch...
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/Value.java, line 52 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWLBWD5Q7deFE6DT0j:-MSWLBWD5Q7deFE6DT0k:b-abm3pt) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/Value.java#L52)):*
> ```Java
>    */
>   default <T> T accept(ValueVisitor<T> visitor) {
>     throw new IllegalArgumentException();
> ```

I'm not sure we need a default value here, as it should be expected to always be implemented? At worst, it should `UnsupportedOperationException` (the reason why `IAE` is used below is that you're supposed to check the value's type before using one of the get method. Personnally, I'm not a big fan of this pattern, and it's less useful once you start adding a visitor pattern...)
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ValueVisitor.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWM_wtDv7Oxjp5LUIv:-MSWM_wtDv7Oxjp5LUIw:bavlfj9) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ValueVisitor.java#L28)):*
> ```Java
>    * @return the possibly transformed value resulting from the visitation.
>    */
>   T visit(Value value);
> ```

This is probably incorrect: Value can be either `ExpressionFunction`, `ExpressionPath` or `Entity`


<!-- Sent from Reviewable.io -->

2021-02-10 08:38 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/741)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @laurentgo and @rymurr)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWMnMZ3BgFzQLT4YlJ:-MTA3A9oCqR0TZNug3x3:bnvlqwc) (no related file):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Could some unit tests be added to check and also provide some examples on how code can be used?
</blockquote></details>

A simple set of tests that uses a visitor to build up string representations showing usage has been added, aligned with what you were hoping for?

---
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ConditionExpressionVisitor.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWMJzmDt3lBpjiRPxM:-MT9z8xPCfVDP19wtGAP:b7ynmtk) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ConditionExpressionVisitor.java#L28)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I'm not sure I see the point of visiting a `ConditionExpression` if there's no branch...
</blockquote></details>

I think the original intent was that a ConditionExpression could consist of multiple and'd ConditionExpressions, which is untrue. It seems that each one really consists of a group of ExpressionFunctions, which are handled by the existing ValueVisitor. With that in mind I'm going to remove this.
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/Value.java, line 52 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWLBWD5Q7deFE6DT0j:-MT9yiBV7VRY-iLta1Tt:b5mtwx0) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/Value.java#L52)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I'm not sure we need a default value here, as it should be expected to always be implemented? At worst, it should `UnsupportedOperationException` (the reason why `IAE` is used below is that you're supposed to check the value's type before using one of the get method. Personnally, I'm not a big fan of this pattern, and it's less useful once you start adding a visitor pattern...)
</blockquote></details>

Makes sense to me - removed the default.
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ValueVisitor.java, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/741#-MSWM_wtDv7Oxjp5LUIv:-MT9ykoE4FSa8vi8M16y:b-3as0el) ([raw file](https://github.com/projectnessie/nessie/blob/1a8091af77ba3a64bcba17669f6b7b5fffdb8b82/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ValueVisitor.java#L28)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

This is probably incorrect: Value can be either `ExpressionFunction`, `ExpressionPath` or `Entity`
</blockquote></details>

Again - makes sense.


<!-- Sent from Reviewable.io -->

2021-02-10 12:12 UTC, rymurr reviewed
lgtm aside from some minor nits, much cleaner since review. thanks! 

Will wait for @laurentgo to approve

2021-02-10 12:12 UTC, rymurr commented on versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ExpressionFunction.java
> +  public ExpressionFunction alias(AliasCollector aliasCollector) {
nit: moving a method just creates extra noise in a pr. please try to avoid in the future

2021-02-10 12:12 UTC, rymurr commented on versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/Value.java
> +   * Default implementation for visitation.
nit: update the doc since the default impl was removed

2021-02-10 15:52 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/741)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @laurentgo, @rymurr, and @stevelorddremio)

___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ExpressionFunction.java, line 108 at r2](https://reviewable.io/reviews/projectnessie/nessie/741#-MSFUfcKDzycROUqN8fH-r2-108:-MTBc_BS0UrPm6vi9YQc:brqvbcf) ([raw file](https://github.com/projectnessie/nessie/blob/1dce53074bec946adc0325fcb5109d9a5e8252fb/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ExpressionFunction.java#L108)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

nit: moving a method just creates extra noise in a pr. please try to avoid in the future
</blockquote></details>

Oop - that shouldn't have happened...reverted the move.


<!-- Sent from Reviewable.io -->

2021-02-10 17:58 UTC, laurentgo approved these changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/741)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @laurentgo, @rymurr, and @stevelorddremio)



<!-- Sent from Reviewable.io -->

2021-02-10 18:15 UTC, rymurr approved these changes

2021-02-10 18:16 UTC, merged