RocksDB rebase and add ConditionExpression handling
projectnessie/nessie pull request #752
Opened 2021-02-02 01:29 UTC by stevelorddremio

2021-02-02 01:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectnessie/nessie?pullRequest=752) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/projectnessie/nessie?pullRequest=752) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: kylep-dremio<br/>:white_check_mark: stevelorddremio<br/>:x: TiffanyLam<br/>:x: tifflhl<br/><hr/>**TiffanyLam** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectnessie/nessie?pullRequest=752) it.</sub>

2021-02-02 01:32 UTC, laurentgo commented
Can you change the description/initial comment with something describing the change?

2021-02-02 02:30 UTC, laurentgo requested changes
> Reviewed 3 of 20 files at r3, 5 of 36 files at r4, 17 of 27 files at r7, 6 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 26 of 40 files reviewed, 22 unresolved discussions (waiting on @stevelorddremio)

___
*[pom.xml, line 144 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVMhnmBcfkxywNe0OK:-MSVMhnmBcfkxywNe0OL:b68e1w0) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/pom.xml#L144)):*
> ```XML
>     <rocksdb.version>6.13.3</rocksdb.version>
>     <reactor.version>2020.0.3</reactor.version>
>     <rocksdb.version>6.13.3</rocksdb.version>
> ```

present twice...
___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java, line 104 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVNJD73JYoJnzRObkH:-MSVNJD73JYoJnzRObkI:bc95wdp) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java#L104)):*
> ```Java
> 
>   @Test
>   void updateAddClause() {
> ```

why removing this test?
___
*[versioned/tiered/mongodb/pom.xml, line 40 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVNqkg1ncg8v_ev-mF:-MSVNqkg1ncg8v_ev-mG:b-lrp1b4) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/versioned/tiered/mongodb/pom.xml#L40)):*
> ```XML
>     <dependency>
>       <groupId>org.projectnessie</groupId>
>       <artifactId>nessie-versioned-tests</artifactId>
> ```

cleanup?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java, line 23 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPF-rDtMKnCRi2eHB:-MSVPF-sEQSlY_x2tNOe:b5xfeaz) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java#L23)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> /**
>  * A set of conditions that are asserted against an Entity.
>  */
> public class Condition {
>   public List<Function> functionList;
>   public Condition() {
>     this.functionList = new ArrayList<>();
>   }
>   public void add(Function holder) {
>     functionList.add(holder);
>   }
> }
> ```
</details>

have you looked at using immutables to create POJOs?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java, line 26 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPKZBAFLt2QT52z_Y:-MSVPKZBAFLt2QT52z_Z:benxofj) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java#L26)):*
> ```Java
> public class Condition {
> 
>   public List<Function> functionList;
> ```

I would recommend against using mutable objects in general, and having mutable public fields. That's a design smell, especially if you are looking at thread safety
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java, line 31 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPjXv6Fahumy5DF_F:-MSVPjXv6Fahumy5DF_G:b-1sfp0n) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java#L31)):*
> ```Java
> 
>   /**
>    * Split a string path to it's separate parts.
> ```

typo: its
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java, line 36 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPu-18elnyu100p6j:-MSVPu-18elnyu100p6k:br2k9xl) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java#L36)):*
> ```Java
>    */
>   static List<String> splitPath(String path) {
>     return Arrays.asList(path.split(Pattern.quote(".")));
> ```

not sure why this method is here, it seems to have nothing to do with evaluation...

Also, `Pattern.quote(".")` is constant, no need to recreate the string with each invocation. But maybe using Guava `Splitter` class might be actually more convenient.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 27 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVTUMMDmhe921TNBVi:-MSVTUMMDmhe921TNBVj:b-9zsz04) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L27)):*
> ```Java
>   public static final String SIZE = "size";
> 
>   final String operator;
> ```

why those fields are not private?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 48 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVRuknDp5o1fNZMdzS:-MSVRuknDp5o1fNZMdzT:b-fqh8b1) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L48)):*
> ```Java
>    * @return true if this is equal to provided object
>    */
>   public boolean equals(Function ex) {
> ```

it is likely not a good idea to not override `boolean equals(Object)`

Here's my scenario:
```
class Foo {
  public boolean equals(Foo that) {
    return false;
  }
  
  public boolean equals(Object object) {
    return true;
  }
}

Foo foo = new Foo();
Foo bar = new Foo();

System.out.println(foo.equals(bar)); // Foo#equals(Foo)
List<Foo> list = Collections.singletonList(foo);
list.contains(bar); // Foo#equals(Object)
```
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 48 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVTMe68I_NATVZekfI:-MSVTMe68I_NATVZekfJ:b-f8tocj) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L48)):*
> ```Java
>    * @return true if this is equal to provided object
>    */
>   public boolean equals(Function ex) {
> ```

what `ex` stands for?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksBaseValue.java, line 70 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVTvFzBdxQRpXoeKek:-MSVTvFzBdxQRpXoeKel:b-4n7tz8) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksBaseValue.java#L70)):*
> ```Java
>   Entity toEntity(Stream<Id> idStream) {
>     List<Id> idList = idStream.collect(Collectors.toList());
>     List<Entity> idsAsEntity = new ArrayList<>();
> ```

you don't need 2 lists: leverage `Stream`...
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksBaseValue.java, line 84 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVUHgzCIfbEcvzW6_e:-MSVUHh-3tTBT_Hr7Nu1:b-op39v9) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksBaseValue.java#L84)):*
> ```Java
>    */
>   Entity toEntity(Stream<Id> idStream, int position) {
>     return idStream.collect(Collectors.toList()).get(position).toEntity();
> ```

`idStream.skip(position).map(Id::toEntity).findFirst().orElse(...)` to avoid fully materializing the stream.. [...]

2021-02-02 16:47 UTC, kylep-dremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 26 of 40 files reviewed, 25 unresolved discussions (waiting on @laurentgo and @stevelorddremio)

___
*[versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 241 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSYZiOk6dlMRRAWBC-P:-MSYZiOl8BQ6TsvwSglv:bz0zp7c) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L241)):*
> ```Java
>   @Override
>   public void save(List<SaveOp<?>> ops) {
>     final Map<ValueType<?>, List<SaveOp<?>>> perType = ops.stream().collect(Collectors.groupingBy(SaveOp::getType));
> ```

Although nice - why has this the MongoDB store changed when this is pertaining to Rocks?
___
*[versioned/tiered/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 70 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSYZuvG6IbyCenv1KaA:-MSYZuvG6IbyCenv1KaB:brhm8rg) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/versioned/tiered/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L70)):*
> ```Java
>   }
> 
>   @Override
> ```

Why removed?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java, line 22 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSY_3nm1IUoWvy3l8Hm:-MSY_3nm1IUoWvy3l8Hn:b-btbqbd) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java#L22)):*
> ```Java
> import java.util.regex.Pattern;
> 
> public interface Evaluator {
> ```

Should have a class comment here being descriptive of the intent.
___
*[versioned/tiered/rocksdb/src/main/proto/value.proto, line 23 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVZTnW5W5QPomfdgKH:-MSY_hMI1uKHj6_XCmK4:balcso4) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/proto/value.proto#L23)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

What happened to using oneof?
</blockquote></details>

Are you saying that only one of id or dt is present? Or something else?
___
*[versioned/tiered/rocksdb/src/main/proto/value.proto, line 25 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVYt7u9jXSJxHjHrbh:-MSYbtGvCePjgQC8f3DT:bb6un1j) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/proto/value.proto#L25)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I know that the field name is `dt` and it was chosen because dynamodb needs small field names, but protobuf doesn't, and so I would suggest to give it a understandable name
</blockquote></details>

Done
___
*[versioned/tiered/rocksdb/src/main/proto/value.proto, line 53 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVZ5hf3JV7TvvCb1p1:-MSYbsRP67ZZ_cyEtbu_:bb6un1j) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/proto/value.proto#L53)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

(style) convention for protobuf fields is snake_case, please stick to it (if someone knows how to validate protobuf files, much appreciated)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-02-02 22:42 UTC, kylep-dremio commented on versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java
> +class Condition {
Have you investigated Immutables yet?

2021-02-02 22:42 UTC, kylep-dremio commented on versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java
> +  boolean equals(Function function) {
This didn't address the problem about Object#equals.

2021-02-04 13:20 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 10 of 39 files reviewed, 40 unresolved discussions (waiting on @laurentgo and @stevelorddremio)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh3LqLEjoYdcjpcipX:-MSh3LqLEjoYdcjpcipY:bmqun4f) (no related file):*
I'm not sure whether we do really need all theoretically possible variants of conditions being coded here. All that relies on `Entity` (which is eventually going away, at least for "public/SPI" consumption) and a lot of the conditions-stuff is tied to DynamoDB.

It's not that easy to have some API for the condition-expressions that is both flexible enough but also not that tied to Dynamo specifics. Until we have that in place, I'd be okay with an implementation that's rather incomplete (wrt to theoretically possible condition-expression-variations), but passes all tests from `AbstractITTieredVersionStore` and `AbstractITVersionStore`.

We cannot tell if the implementation is sufficient, without RocksDB implementations for `AbstractITTieredVersionStore` and `AbstractITVersionStore`.

---
___
*[versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 244 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSgzvuC95xpr0y1TzUx:-MSgzvuC95xpr0y1TzUy:bcwy6uy) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L244)):*
> ```Java
> 
>     Flux.fromIterable(perType.entrySet())
>       .flatMap(entry -> ((MongoCollection) writeCollection(entry.getKey()))
> ```

This is still an unchecked-cast that deserves a `@SuppressWarning`
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 26 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh6SJ1Aex4CFS35BY7:-MSh6SJ1Aex4CFS35BY8:b-dx0q7a) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L26)):*
> ```Java
> class Function {
>   public static final String EQUALS = "equals";
>   public static final String SIZE = "size";
> ```

Nit: no need for `public` here, if the class is package-protected
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 49 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh6g2m1zgHhVBXQ7hi:-MSh6g2m1zgHhVBXQ7hj:bcqpp2a) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L49)):*
> ```Java
>    * @return true if this is equal to provided object
>    */
>   boolean equals(Function function) {
> ```

When implementing `equals(Object)`, please pair it with `hashCode()`.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksRef.java, line 216 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh2GGs7JAkjozbp__P:-MSh2GGs7JAkjozbp__Q:b-w1p9h3) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksRef.java#L216)):*
> ```Java
>     checkPresent(type, TYPE);
> 
>     final ValueProtos.Ref.Builder builder = ValueProtos.Ref.newBuilder().setBase(buildBase()).setName(name);
> ```

i'd really prefer to serialize all properties values directly into the protobuf-builder instead of first buffering the properties in fields and then to copy the buffered properties into the protobuf-builder.
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/IdMap.java, line 43 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh-nhg4ibYjO2JJ4WD:-MSh-nhg4ibYjO2JJ4WE:b-hr8fi7) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/IdMap.java#L43)):*
> ```Java
>  * of their original state so one can see what items changed over time.
>  */
> public class IdMap implements Iterable<Id> {
> ```

Please revert this. All classes in `com.dremio.nessie.versioned.impl` are really only for the `TieredVersionStore`.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 71 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MShAUw-0Wd8EpnXYBby:-MShAUw01a-XBCyOVMns:b-cym5xa) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L71)):*
> ```Java
>   private static final Logger LOGGER = LoggerFactory.getLogger(RocksDBStore.class);
>   private static final long OPEN_SLEEP_MILLIS = 100L;
>   private static final List<byte[]> COLUMN_FAMILIES;
> ```

This is only used during initialization, but kept around forever.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 75 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh7tqH168dArClcmcT:-MSh7tqH168dArClcmcU:b8na2xa) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L75)):*
> ```Java
> 
>   static {
>     RocksDB.loadLibrary();
> ```

Q: Does this work on all platforms (Linux, OSX and maybe Windows)?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 78 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh89GE1JXB8BlKBgs9:-MSh89GE1JXB8BlKBgsA:bnq6t6z) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L78)):*
> ```Java
>     COLUMN_FAMILIES = Stream.concat(
>       Stream.of(RocksDB.DEFAULT_COLUMN_FAMILY),
>       ValueType.values().stream().map(v -> v.name().getBytes(UTF_8))).collect(ImmutableList.toImmutableList());
> ```

`Collectors.toList()` or `toUnmodifiableList()`should be sufficient here.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 100 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh8Vb273XFyUYTlTm7:-MSh8Vb273XFyUYTlTm8:b-9zeqpi) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L100)):*
> ```Java
> 
>     // TODO: currently an infinite loop, need to configure
>     while (true) {
> ```

Why do you need this loop at all? What guarantees that a 2nd or 3rd iteration succeeds?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 107 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh96xp2lRdknPq4UYE:-MSh96xp2lRdknPq4UYF:bp8gm9j) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L107)):*
> ```Java
>         rocksDB = transactionDB.getBaseDB();
>         valueTypeToColumnFamily = IntStream.rangeClosed(1, ValueType.values().size()).boxed().collect(
>           ImmutableMap.toImmutableMap(k -> ValueType.values().get(k - 1), columnFamilyHandles::get));
> ```

I'd prefer `Collectors.toMap` or `Collectors.toUnmodifiableMap` here
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 107 at r10]( [...]

2021-02-09 02:16 UTC, laurentgo requested changes
> Reviewed 5 of 22 files at r11.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 10 of 39 files reviewed, 35 unresolved discussions (waiting on @laurentgo, @snazy, and @stevelorddremio)

___
*[pom.xml, line 139 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT27X21El_-o7g9-_xM:-MT27X21El_-o7g9-_xN:bci78je) ([raw file](https://github.com/projectnessie/nessie/blob/c2c571d25e2317812866b20705fee62bf68fb219/pom.xml#L139)):*
> ```XML
>     <logback.version>1.2.3</logback.version>
>     <protobuf.version>3.14.0</protobuf.version>
>     <protobug.maven.version>0.6.1</protobug.maven.version>
> ```

is `protobug` a typo? Also, not all versions should have a property (at least for single artifacts/plugins)
___
*[pom.xml, line 682 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT27rld7iEau0kAYCzT:-MT27rld7iEau0kAYCzU:b-ufnebt) ([raw file](https://github.com/projectnessie/nessie/blob/c2c571d25e2317812866b20705fee62bf68fb219/pom.xml#L682)):*
> ```XML
>             <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
>           </configuration>
>           <executions>
> ```

executions should not be mentioned in pluginManagement
___
*[servers/quarkus-server/pom.xml, line 210 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT28rnC2sL23z60KXAy:-MT28rnC2sL23z60KXAz:b-jrgr6h) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/servers/quarkus-server/pom.xml#L210)):*
> ```XML
>           <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
>         </configuration>
>         <executions>
> ```

execution should be kept (also a good id to give it an id). If you want to share config (for example, output directory location, that part can be moved to pluginManagement (under the general configuration, but could clash later with test-compile). Another option is to use the default value (which is probably fine too)
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 27 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVTUMMDmhe921TNBVi:-MT2BGTbEMmr2ft_yxI7:b-5ybq55) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L27)):*
> ```
> operator
> ```
or also, why not making an enum out of operator?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 38 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT2A1g44Ri1Fr0RQtdV:-MT2A1g44Ri1Fr0RQtdW:b-f9egg4) ([raw file](https://github.com/projectnessie/nessie/blob/c2c571d25e2317812866b20705fee62bf68fb219/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L38)):*
> ```Java
>    * @return true if this is equal to provided object
>    */
>   @Override
> ```

if you use Immutables, do you need to implement `equals` and `hashCode` yourself?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 87 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT2AUIaD3OtRsOLSfBi:-MT2AUIb1CtG6Uywhv6f:brvwjfm) ([raw file](https://github.com/projectnessie/nessie/blob/c2c571d25e2317812866b20705fee62bf68fb219/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L87)):*
> ```Java
>    * @return true if this function relates to a EQUALS evaluation.
>    */
>   boolean isEquals() {
> ```

this is usually not a good pattern (or at least a pattern which doesn't scale for sure). At least I would recommend this type of the business logic in the class using it vs in the POJO (same for related methods)
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksBaseValue.java, line 100 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVUyueERQri87DMZs1:-MT3WJbG6QrN01ZyGfkI:b2786wh) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksBaseValue.java#L100)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

why this logic is embedded into basevalue vs evaluator/function?
</blockquote></details>

to detail a bit more. Since function is a POJO, evaluator is probably the place where the evaluation logic should be done.
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ConditionExpressionVisitor.java, line 23 at r12](https://reviewable.io/reviews/projectnessie/nessie/752#-MT3ZQBIElV3gTloDkAj:-MT3ZQBIElV3gTloDkAk:b-htmasf) ([raw file](https://github.com/projectnessie/nessie/blob/b923f1433cb5664befc5f02079025e68dc83ec4d/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ConditionExpressionVisitor.java#L23)):*
> ```Java
>  * @param <T> The class to which the ConditionExpression will be converted.
>  */
> public interface ConditionExpressionVisitor<T> {
> ```

do we need a visitor which only has one case to visit?
___
*[versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ValueVisitor.java, line 28 at r12](https://reviewable.io/reviews/projectnessie/nessie/752#-MT3ZZaxEmw8dKhmkjh2:-MT3ZZaxEmw8dKhmkjh3:b-d2hy2l) ([raw file](https://github.com/projectnessie/nessie/blob/b923f1433cb5664befc5f02079025e68dc83ec4d/versioned/tiered/tiered-impl/src/main/java/com/dremio/nessie/versioned/impl/condition/ValueVisitor.java#L28)):*
> ```Java
>    * @return the possibly transformed value resulting from the visitation.
>    */
>   T visit(Value value);
> ```

I mentioned it in your standalone patch. Do you plan to merge that change first, or to integrate it into this change?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 75 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh7tqH168dArClcmcT:-MT3WqBhBj0U-IXIXz9Y:b-8oegm3) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L75)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Q: Does this work on all platforms (Linux, OSX and maybe Windows)?
</blockquote></details>

(yes)
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 78 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh89GE1JXB8BlKBgs9:-MT2C8-pAMV1uFK0Jjkc:bejl3er) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L78)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

`Collectors.toList()` or `toUnmodifiableList()`should be sufficient here.
</blockquote></details>

Not quite? `Collectors.toList()` is not unmodifiable, and `Collectors.toUnmodifiableList()` is not available in JDK8 (introduced in Java10)
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 100 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh8Vb273XFyUYTlTm7:-MT3WxT8AvXi1_CJv7Uu:b-3u5gm3) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L100)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Why do you need this loop at all? What guarantees that a 2nd [...]

2021-02-10 20:28 UTC, stevelorddremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 8 of 39 files reviewed, 35 unresolved discussions (waiting on @kylep-dremio, @laurentgo, @snazy, and @stevelorddremio)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh3LqLEjoYdcjpcipX:-MTCao5s467M3JUSHexe:b-ps48py) (no related file):*
> AbstractITTieredVersionStore and AbstractITVersionStore
I think we will address this when we wire in RocksDB as an available nessie store. Does this make sense?

---
___
*[pom.xml, line 144 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVMhnmBcfkxywNe0OK:-MSYUyrODV40uC1aq_EB:b-f06npo) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/pom.xml#L144)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

present twice...
</blockquote></details>

Dup removed.
___
*[pom.xml, line 682 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT27rld7iEau0kAYCzT:-MTCc6kD3s6woSWGxJZL:boey76l) ([raw file](https://github.com/projectnessie/nessie/blob/c2c571d25e2317812866b20705fee62bf68fb219/pom.xml#L682)):*
> ```
> org.xolstice.maven.plugins
> ```
We will move the execution back out to the projects where they are used. quarkus-server and rocksdb.
___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java, line 104 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVNJD73JYoJnzRObkH:-MSYY8y71azc4Q4-i08Y:bparmrk) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/condition/TestExpressions.java#L104)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

why removing this test?
</blockquote></details>

If you mean removing the if_not_exists test, this comes from a comment in nessie-public Slack December 21:

Jacques Nadeau 1:58 PM
It looks like you're referring to the static SetClause.ifNotExists method. If we're not using it anywhere, yes, makes sense to remove. (edited) 
___
*[versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 241 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSYZiOk6dlMRRAWBC-P:-MSYg3AO07KMsYZ92vky:b-sgt2p4) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L241)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Although nice - why has this the MongoDB store changed when this is pertaining to Rocks?
</blockquote></details>

Agreed nice. This was your change.
___
*[versioned/tiered/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java, line 70 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSYZuvG6IbyCenv1KaA:-MSYgLIWCxuT57FizKVH:b-fv6esb) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/versioned/tiered/mongodb/src/test/java/com/dremio/nessie/versioned/store/mongodb/TestMongoDBStore.java#L70)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Why removed?
</blockquote></details>

This was your change.


<!-- Sent from Reviewable.io -->

2021-02-11 05:32 UTC, stevelorddremio commented
Closing PR as merging seems odd. Will open new one when rectified.

2021-02-11 05:32 UTC, closed without merging

2021-02-12 00:22 UTC, stevelorddremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 4 of 146 files reviewed, 34 unresolved discussions (waiting on @kylep-dremio, @laurentgo, @snazy, and @stevelorddremio)

___
*[servers/quarkus-server/pom.xml, line 210 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT28rnC2sL23z60KXAy:-MTH0lwI4IzCuEcdm6kX:b-7ihl7j) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/servers/quarkus-server/pom.xml#L210)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

execution should be kept (also a good id to give it an id). If you want to share config (for example, output directory location, that part can be moved to pluginManagement (under the general configuration, but could clash later with test-compile). Another option is to use the default value (which is probably fine too)
</blockquote></details>

Kept execution here and move rest of plugin config to main pom.xml. Change will appear in new PR soon.
___
*[versioned/tiered/mongodb/pom.xml, line 40 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVNqkg1ncg8v_ev-mF:-MTI_8mL7Tv3pmWg7mQ6:b2nhswy) ([raw file](https://github.com/projectnessie/nessie/blob/1eddd8da3652b55ba6a5d0a267aaf68be3f4dd24/versioned/tiered/mongodb/pom.xml#L40)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

cleanup?
</blockquote></details>

Yes
___
*[versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java, line 244 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSgzvuC95xpr0y1TzUx:-MTI_Aor6LoTnMGazkR_:bb6un1j) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoDBStore.java#L244)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

This is still an unchecked-cast that deserves a `@SuppressWarning`
</blockquote></details>

Done
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java, line 23 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPF-rDtMKnCRi2eHB:-MTH3WXh2UYywhNUaAQF:b-8jznd5) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java#L23)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
> /**
>  * A set of conditions that are asserted against an Entity.
>  */
> public class Condition {
>   public List<Function> functionList;
>   public Condition() {
>     this.functionList = new ArrayList<>();
>   }
>   public void add(Function holder) {
>     functionList.add(holder);
>   }
> }
> ```
have you looked at using immutables to create POJOs?
</blockquote></details>

yes, we have changed Function.java to Immutable, although Condition class has been refactored out
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java, line 26 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPKZBAFLt2QT52z_Y:-MTH4ha_6EXQP9914C1X:bodg1po) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java#L26)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I would recommend against using mutable objects in general, and having mutable public fields. That's a design smell, especially if you are looking at thread safety
</blockquote></details>

Agreed. Now using Immutable for Function.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java, line 26 at r9](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVLyxNS2slqp4o_IA7-r9-26:-MTH4OaS8hLBrM2RTWee:b-jjcqo9) ([raw file](https://github.com/projectnessie/nessie/blob/c6b926e145b9447f1310bdcb2df0003151ae8f9c/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Condition.java#L26)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Have you investigated Immutables yet?
</blockquote></details>

Yes, this is implemented for Function.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java, line 22 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSY_3nm1IUoWvy3l8Hm:-MTH4uAX-vn3MzYZNn3r:b-cyl3gw) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java#L22)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

Should have a class comment here being descriptive of the intent.
</blockquote></details>

Yes, this has been added.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java, line 36 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVPu-18elnyu100p6j:-MTHBWKp1pSOj-K02Xj3:bmdhd4o) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Evaluator.java#L36)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

not sure why this method is here, it seems to have nothing to do with evaluation...

Also, `Pattern.quote(".")` is constant, no need to recreate the string with each invocation. But maybe using Guava `Splitter` class might be actually more convenient.
</blockquote></details>

this has now been refactored out.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 27 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVTUMMDmhe921TNBVi:-MTI_KJOEg7t8y5piXfa:bhp4f2x) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L27)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
> operator
> ```
or also, why not making an enum out of operator?
</blockquote></details>

Agreed, now an enum
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 48 at r8](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVTMe68I_NATVZekfI:-MTI_GZI7jl9LGxnCUKj:bhbvz1p) ([raw file](https://github.com/projectnessie/nessie/blob/259ee0c88ba29988530c28f3dbe6b6aae2b954ea/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L48)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

what `ex` stands for?
</blockquote></details>

Expression. Now renamed
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 48 at r9](https://reviewable.io/reviews/projectnessie/nessie/752#-MSVLyxNS2slqp4o_IA9-r9-48:-MTIazPlB0Hkhg5vlUIH:bvm7z8d) ([raw file](https://github.com/projectnessie/nessie/blob/c6b926e145b9447f1310bdcb2df0003151ae8f9c/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java#L48)):*
<details><summary><i>Previously, kylep-dremio wrote…</i></summary><blockquote>

This didn't address the problem about Object#equals.
</blockquote></details>

Resolved
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/Function.java, line 26 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh6SJ1Aex4CFS35BY7:-MTI_NjL0h96fb4lwQDP:bb6un1j) ([raw file](https://github.com/ [...]

2021-02-12 01:28 UTC, stevelorddremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 4 of 146 files reviewed, 34 unresolved discussions (waiting on @kylep-dremio, @laurentgo, @snazy, and @stevelorddremio)

___
*[pom.xml, line 139 at r11](https://reviewable.io/reviews/projectnessie/nessie/752#-MT27X21El_-o7g9-_xM:-MTIlRNYBZh4jcQuO-17:b-sv7ux4) ([raw file](https://github.com/projectnessie/nessie/blob/c2c571d25e2317812866b20705fee62bf68fb219/pom.xml#L139)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is `protobug` a typo? Also, not all versions should have a property (at least for single artifacts/plugins)
</blockquote></details>

Yes, should be protobuf. Corrected. I think all versions in one place centralizes that info.
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 75 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh7tqH168dArClcmcT:-MTImRK44x1C5y2vfDcY:b-rk2ucf) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L75)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

(yes)
</blockquote></details>

This looks like it is answered. True?
___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 107 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MSh96xp2lRdknPq4UYE:-MTIn2S8AuQhFB3peWrr:b-ady44f) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L107)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

see my comment above. For unmodifiable collections, Guava seems currently the best choice
</blockquote></details>

this uses Guava ImmutableMap. Does that answer your concern?


<!-- Sent from Reviewable.io -->

2021-02-12 05:01 UTC, stevelorddremio reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/752)* status: 4 of 146 files reviewed, 34 unresolved discussions (waiting on @kylep-dremio, @laurentgo, @snazy, and @stevelorddremio)

___
*[versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java, line 270 at r10](https://reviewable.io/reviews/projectnessie/nessie/752#-MShBKfn6GzlMKIagm-q:-MTIyL0i8lfmQ0XVyPL8:b-oztdvt) ([raw file](https://github.com/projectnessie/nessie/blob/2570af6695a0bcb2cecc5e0faaaa4e258d497b5d/versioned/tiered/rocksdb/src/main/java/com/dremio/nessie/versioned/store/rocksdb/RocksDBStore.java#L270)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

nothing, really... a Stream might be more appropriate possibly.
</blockquote></details>

Rocks only exposes an Iterator, so not sure there is a better way.


<!-- Sent from Reviewable.io -->