Add metrics and tracing to dynamo store
projectnessie/nessie pull request #755
Opened 2021-02-02 09:01 UTC by rymurr

This does the following:

* adds a metrics publisher for [aws sdk2](https://aws.amazon.com/blogs/developer/using-the-new-client-side-metrics-feature-in-the-aws-sdk-for-java-v2/)
* adds an option to each SDK request to return consumed capacity values
* adds an interceptor to capture Dynamo consumed capacity and convert to metrics
* adds an opentracing interceptor for dynamo

2021-02-03 21:17 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @rymurr and @snazy)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 138 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSde9kd84KO4eRABfNI:-MSde9kd84KO4eRABfNJ:bjgy0zf) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L138)):*
> ```Java
>     try {
>       DynamoMetricsPublisher publisher = new DynamoMetricsPublisher();
>       TracingExecutionInterceptor tracing = new TracingExecutionInterceptor(GlobalTracer.get());
> ```

I wonder if this should be resolved when the plugin is started vs at the time it's being accessed. Being a global state, it means it could be changed later on, but the store would not pick up the change.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 205 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdehb35RozVKJnIc8t:-MSdehb35RozVKJnIc8u:b2d4pd2) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L205)):*
> ```Java
>         }));
> 
>         BatchGetItemResponse response = client.batchGetItem(BatchGetItemRequest.builder().requestItems(loads).returnConsumedCapacity(
> ```

shouldn't the interceptor do it?
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 60 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdjqi11HQT7iuNvvp8:-MSdjqi11HQT7iuNvvp9:b-d0patt) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L60)):*
> ```Java
>  */
> public class DynamoMetricsPublisher implements MetricPublisher {
>   private static final Map<String, Timer> TIMER_CACHE = new HashMap<>();
> ```

this is definitively not thread safe...
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 67 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdgvKY9XXJACGmlKwo:-MSdgvKZBCa-uqR6X8ss:b-9mqzm8) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L67)):*
> ```
>     AtomicReference<String> operationName = new AtomicReference<>("unknown");
>     AtomicReference<String> serviceId = new AtomicReference<>("unknown");
> ```
trick: you can use an single element array too

That said, it looks like you could do `String operationName = Iterables.getFirst(metricCollection.metricValue(CoreMetric.OperationName), "unknown")`
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 70 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdh9bI5hc90_vUfvTP:-MSdh9bI5hc90_vUfvTQ:ba7llfq) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L70)):*
> ```Java
>     metricCollection.stream().forEach(r -> {
>       String name = r.metric().name();
>       if (name.equals("OperationName")) {
> ```

(style) let's use a switch + string constants (doesn't AWS have some already)?


<!-- Sent from Reviewable.io -->

2021-02-04 11:48 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 4 files reviewed, 19 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 144 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgpCVr-5SbJRJv3G5W:-MSgpCVr-5SbJRJv3G5X:bcx0d9p) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L144)):*
> ```Java
>       b1.httpClient(UrlConnectionHttpClient.create());
>       DynamoDbAsyncClientBuilder b2 =
>           DynamoDbAsyncClient.builder().overrideConfiguration(x -> x.addExecutionInterceptor(publisher.interceptor())
> ```

Would be nicer to have a method that applies this here and above.

Having a configuration to opt-out would be nice. I.e. tracing+metrics are enabled by default, but people can turn it off, just in case.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 60 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdjqi11HQT7iuNvvp8:-MSgi2sq4UEi7cVwtHiB:b-iy8otk) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L60)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

this is definitively not thread safe...
</blockquote></details>

yup, maybe just use a `ConcurrentHashMap`
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 63 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgkx1yDZTdUWgez5CQ:-MSgkx1yDZTdUWgez5CR:b-xmy6st) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L63)):*
> ```Java
>   private static final Map<String, AtomicInteger> GAUGE_CACHE = new HashMap<>();
>   private static final Map<String, DistributionSummary> COUNTER_CACHE = new HashMap<>();
> ```

Hint: Better add a default, no-arg constructor. Future Java versions will require that.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgiX_l8FZ8KQGt9TqB:-MSgiX_l8FZ8KQGt9TqC:b-xvteoq) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L68)):*
> ```Java
>     AtomicReference<String> operationName = new AtomicReference<>("unknown");
>     AtomicReference<String> serviceId = new AtomicReference<>("unknown");
>     metricCollection.stream().forEach(r -> {
> ```

You can change it to an "old school" `for (MetricRecord<?> r : metricCollecton)`, so you save both the two `AtomicReference` instances, the unnecessary "volatile" read-writes and the spliterator/stream-instances. `software.amazon.awssdk.metrics.MetricCollection#stream` always delegates to a `Spliterator`.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 87 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgjg8n0xPWPTfe5o7d:-MSgjg8n0xPWPTfe5o7e:bc6694u) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L87)):*
> ```Java
>       String key = String.format("%s/%s/%s", metricName, level, operationName);
>       Tags tags = Tags.of("level", level, "operation", operationName);
>       if (Duration.class.equals(m.metric().valueClass())) {
> ```

It's a `Class`, mind changing this to `==`?
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 87 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgkC5fBIOYq6oH3Usw:-MSgkC5fBIOYq6oH3Usx:b-jcbzdn) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L87)):*
> ```Java
>       String key = String.format("%s/%s/%s", metricName, level, operationName);
>       Tags tags = Tags.of("level", level, "operation", operationName);
>       if (Duration.class.equals(m.metric().valueClass())) {
> ```

Can you get `m.metric().valueClass()` into a separate variable and use that all the way along below?
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 91 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgjkw37_GxP_8MLaZ1:-MSgjkw4Dz2S1L8moe1u:b5c3ob6) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L91)):*
> ```Java
>         Duration duration = (Duration) value;
>         timer.record(duration.toNanos(), TimeUnit.NANOSECONDS);
>       } else if (Integer.class.equals(m.metric().valueClass()) || Boolean.class.equals(m.metric().valueClass())) {
> ```

It's a `Class`, mind changing these to `==`?
I'd prefer to split this into two distinct branches instead of ("if (c == Integer || c == Boolean) { ... if (c == Integer) { ... } else { ... } ... }")
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 92 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgkcMz31o6BmcirOr4:-MSgkcMz31o6BmcirOr5:bum9esl) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L92)):*
> ```Java
>         timer.record(duration.toNanos(), TimeUnit.NANOSECONDS);
>       } else if (Integer.class.equals(m.metric().valueClass()) || Boolean.class.equals(m.metric().valueClass())) {
>         Integer intValue;
> ```

use the primitive `int` here
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 97 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgkiKACacMZM3PPjOR:-MSgkiKACacMZM3PPjOS:b-tqn9sn) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L97)):*
> ```Java
>         } else {
>           Boolean boolValue = (Boolean) value;
>           intValue = boolValue ? 1 : 0;
> ```

use the primitive `boolean` here and inline into a single line
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 99 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSghzfx2n9xPxj9ujPN:-MSghzfx2n9xPxj9ujPO:bxof3vn) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L99)):*
> ```Java
>           intValue = boolValue ? 1 : 0;
>         }
>         measure(key, metricName, tags, (int) intValue);
> ```

nit: unnecessary cast
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dyna [...]

2021-02-04 13:49 UTC, rymurr reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 4 files reviewed, 17 unresolved discussions (waiting on @laurentgo and @snazy)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 138 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSde9kd84KO4eRABfNI:-MSgAdYe32n9uvSqHpOG:b-k5k4l1) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L138)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I wonder if this should be resolved when the plugin is started vs at the time it's being accessed. Being a global state, it means it could be changed later on, but the store would not pick up the change.
</blockquote></details>

not sure what you mean, sorry. The `Tracer` is needed to add the interceptor which is needed at construction time of the client.

We could theoretically override every dynamo call individually to add the interceptors but that adds a lot of noise.

Finally, I think once the tracer is started i doubt it will be changing, its certainly outside the scope of what Quarkus does
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 144 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgpCVr-5SbJRJv3G5W:-MSgxOQ1EV1PyZF2llKy:bwco60l) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L144)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Would be nicer to have a method that applies this here and above.

Having a configuration to opt-out would be nice. I.e. tracing+metrics are enabled by default, but people can turn it off, just in case.
</blockquote></details>

added the method, it looks kinda goofy because the two builders dont have a base interface so its not easy to make it nicely reusable. 

Added a config
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 205 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdehb35RozVKJnIc8t:-MSh11UZ43SJBD-6wTh4:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L205)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

shouldn't the interceptor do it?
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 60 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdjqi11HQT7iuNvvp8:-MSh18x-EGwAiHbsEk2o:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L60)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

yup, maybe just use a `ConcurrentHashMap`
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 63 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgkx1yDZTdUWgez5CQ:-MSh1C4a3b_Ck5ZlQqni:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L63)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Hint: Better add a default, no-arg constructor. Future Java versions will require that.
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 67 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdgvKY9XXJACGmlKwo:-MSh2ZJZAst8MIL4mcul:b4u4qyy) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L67)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

> ```
>     AtomicReference<String> operationName = new AtomicReference<>("unknown");
>     AtomicReference<String> serviceId = new AtomicReference<>("unknown");
> ```
trick: you can use an single element array too

That said, it looks like you could do `String operationName = Iterables.getFirst(metricCollection.metricValue(CoreMetric.OperationName), "unknown")`
</blockquote></details>

switched to `for` loop
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 68 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgiX_l8FZ8KQGt9TqB:-MSh2a6m5xD9hVbQ4Bq4:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L68)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

You can change it to an "old school" `for (MetricRecord<?> r : metricCollecton)`, so you save both the two `AtomicReference` instances, the unnecessary "volatile" read-writes and the spliterator/stream-instances. `software.amazon.awssdk.metrics.MetricCollection#stream` always delegates to a `Spliterator`.
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 70 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdh9bI5hc90_vUfvTP:-MSh2l8r8Fj6NB3kFGnh:b-p3ruk3) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L70)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

(style) let's use a switch + string constants (doesn't AWS have some already)?
</blockquote></details>

They don't have string constants that I am aware of. Switched to using the static metrics though
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 87 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgjg8n0xPWPTfe5o7d:-MSh34SM7WcQ4Up2VE9i:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L87)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

It's a `Class`, mind changing this to `==`?
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 87 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgkC5fBIOYq6oH3Usw:-MSh3E3x2RpKjoCyCd-K:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L87)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Can you get `m.metric().valueClass()` into a separate variable and use that all the  [...]

2021-02-04 16:01 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 144 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgpCVr-5SbJRJv3G5W:-MShjPPo8ph65cgukffi:b-pggz11) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L144)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

added the method, it looks kinda goofy because the two builders dont have a base interface so its not easy to make it nicely reusable. 

Added a config
</blockquote></details>

ah, bummer. didn't notice that those dynamo-API don't share a common interface for that `overrideConfiguration`. Yea, it looks a bit ugly. I wouldn't mind to revert this then.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 67 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSdgvKY9XXJACGmlKwo:-MShl1w7Da4fn5OGneNV:bgf827c) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L67)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

switched to `for` loop
</blockquote></details>

Much nicer :)
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 118 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSghTrp8J0PGg7f6WMC:-MShlHMb0BXI-uZSAnlJ:bb6vmix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L118)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

for the time being I have left off...curious what others think? I don't really want to complicate the config and I dont know what our SLOs should be. Have just left the percentile histogram, which should be enough for us now
</blockquote></details>

Fair
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 93 at r2](https://reviewable.io/reviews/projectnessie/nessie/755#-MShkmVY5EsfkqhNh4n6:-MShkmVY5EsfkqhNh4n7:byii8mb) ([raw file](https://github.com/projectnessie/nessie/blob/02f72da991dd41ff120546d80bcdf523e79e0949/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L93)):*
> ```Java
>   static {
>     CONSUMED_CAPACITY = ImmutableMap.<Class<? extends SdkResponse>, ToDoubleFunction<SdkResponse>>builder()
>       .put(PutItemResponse.class,
> ```

Would this look a bit nicer, when the whole `put()` is on a single line?


<!-- Sent from Reviewable.io -->

2021-02-04 16:04 UTC, snazy reviewed
Maybe there's a nicer way to format the `static` init in `DynamoMetricsPublisher`.

It would also be nice to have some rudimentary unit test that verifies that the metrics return something. We cannot really assert on any `Duration` and probably only whether some `count > 0` or so. I'd be okay if there are 2 or 3 existing test-cases overridden for dynamo that do that "metrics-smoke-test".

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755#-:-MShlnPtBFXUt0BrY45q:bi7j501)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @laurentgo and @rymurr)



<!-- Sent from Reviewable.io -->

2021-02-05 12:34 UTC, rymurr reviewed
added a test, can easily add more but this asserts that generally the metrics we want are getting created and have sane values

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755#-:-MSmAlxICybJ6AjCECDm:b-i75mid)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 144 at r1](https://reviewable.io/reviews/projectnessie/nessie/755#-MSgpCVr-5SbJRJv3G5W:-MSlo1k_0YWLvrb6LWIE:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/b8e73df3282ec615759987914c97a9999eb43207/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L144)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

ah, bummer. didn't notice that those dynamo-API don't share a common interface for that `overrideConfiguration`. Yea, it looks a bit ugly. I wouldn't mind to revert this then.
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 93 at r2](https://reviewable.io/reviews/projectnessie/nessie/755#-MShkmVY5EsfkqhNh4n6:-MSlo6g88s5-B_rK73Zu:b-auusig) ([raw file](https://github.com/projectnessie/nessie/blob/02f72da991dd41ff120546d80bcdf523e79e0949/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L93)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Would this look a bit nicer, when the whole `put()` is on a single line?
</blockquote></details>

yeah, played around to put them on single lines


<!-- Sent from Reviewable.io -->

2021-02-05 12:49 UTC, snazy requested changes

2021-02-05 12:49 UTC, snazy commented on versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java
> +          String metricName = "DynamoDD.RequestedRecordCount";
```suggestion
          String metricName = "DynamoDB.RequestedRecordCount";
```

2021-02-05 12:50 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 253 at r3](https://reviewable.io/reviews/projectnessie/nessie/755#-MSmDqqs5T5RZKTQsDqA:-MSmDqqt6sfWFMPnmFp9:b5z1ryp) ([raw file](https://github.com/projectnessie/nessie/blob/6a6539740bbbf0b8330f243d23716ff2542072b0/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L253)):*
> ```Java
> 
>         if (count != null) {
>           String metricName = "DynamoDD.RequestedRecordCount";
> ```

DynamoDD ??


<!-- Sent from Reviewable.io -->

2021-02-05 12:51 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoMetrics.java, line 75 at r3](https://reviewable.io/reviews/projectnessie/nessie/755#-MSmEs5614li-NXjiyFE:-MSmEs5614li-NXjiyFF:b-el4u79) ([raw file](https://github.com/projectnessie/nessie/blob/6a6539740bbbf0b8330f243d23716ff2542072b0/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoMetrics.java#L75)):*
> ```Java
>     DistributionSummary putCapacity = (DistributionSummary) meters.stream().findFirst().get();
>     Assertions.assertEquals(4, putCapacity.count());
>     Assertions.assertEquals(10.0, putCapacity.totalAmount());
> ```

I guess, it's better to just assert on > 0 or so


<!-- Sent from Reviewable.io -->

2021-02-05 12:53 UTC, rymurr reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java, line 253 at r3](https://reviewable.io/reviews/projectnessie/nessie/755#-MSmDqqs5T5RZKTQsDqA:-MSmF49B8Vsf8i47c7rJ:b8h2s3) ([raw file](https://github.com/projectnessie/nessie/blob/6a6539740bbbf0b8330f243d23716ff2542072b0/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/metrics/DynamoMetricsPublisher.java#L253)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

DynamoDD ??
</blockquote></details>

good eye
___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoMetrics.java, line 75 at r3](https://reviewable.io/reviews/projectnessie/nessie/755#-MSmEs5614li-NXjiyFE:-MSmFANN2iRjuP24ecI-:b8vaddh) ([raw file](https://github.com/projectnessie/nessie/blob/6a6539740bbbf0b8330f243d23716ff2542072b0/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoMetrics.java#L75)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

I guess, it's better to just assert on > 0 or so
</blockquote></details>

I would rather assert the value...if that changes then the impl changes which is worth knowinng about imho

its isolated from other unit tests so its only if the put impl changes significantly


<!-- Sent from Reviewable.io -->

2021-02-05 14:10 UTC, rymurr reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/755)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoMetrics.java, line 75 at r3](https://reviewable.io/reviews/projectnessie/nessie/755#-MSmEs5614li-NXjiyFE:-MSmWmyNCJJyqGpdfT5t:b7uu04p) ([raw file](https://github.com/projectnessie/nessie/blob/6a6539740bbbf0b8330f243d23716ff2542072b0/versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/impl/ITDynamoMetrics.java#L75)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I would rather assert the value...if that changes then the impl changes which is worth knowinng about imho

its isolated from other unit tests so its only if the put impl changes significantly

</blockquote></details>

I ended up switching it back to your suggestion. The code is dependent on which order the tests run and I dont know enough micrometer to decouple it.


<!-- Sent from Reviewable.io -->

2021-02-05 15:45 UTC, snazy approved these changes
LGTM, as long as the last commits fix the build ;) ;)

2021-02-05 15:51 UTC, merged