Moved TableCommitMetaStoreWorker to nessie-services
projectnessie/nessie pull request #783
Opened 2021-02-08 22:48 UTC by brunos-bq

In this PR, I am moving the class TableCommitMetaStoreWorker from the nessie-quarkus subproject to the nessie-services project.

The reason for this move is to facilitate embedding Nessie within other projects.
Standalone Nessie runs through Quarkus. Embedding Nessie into another project will probably not use Quarkus.

In order to create a VersionStore, a StoreWorker is needed. Prior to that change, projects would have to depend on nessie-quarkus in order to instantiate a StoreWorker.

With this change, projects will now only depend on nessie-model and nessie-services, not importing anything related to Quarkus.

2021-02-08 22:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/projectnessie/nessie?pullRequest=783) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/projectnessie/nessie?pullRequest=783) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/projectnessie/nessie?pullRequest=783) it.</sub>

2021-02-08 23:00 UTC, jacques-n reviewed
While I can see the utility of possibly exposing some of this functionality outside the quarkus-server module, it doesn't seem it should be moved to the services module. What do you think @rymurr and @laurentgo ?

> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783#-:-MT2rgMW5pLh8TrorVz-:b1zgz9n)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-09 01:57 UTC, laurentgo commented
I would agree with @jacques-n : `services` module has been designed to be store-agnostic, so there's no good reason to bring specific code to this module. I'm not saying that the integration between services and the tiered store in quarkus is great either though...

2021-02-09 01:59 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @brunos-bq)

___
*[servers/services/pom.xml, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT3Vggq6N-JGPJoA8_U:-MT3Vggq6N-JGPJoA8_V:b-50nzx2) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/pom.xml#L40)):*
> ```XML
>     <dependency>
>       <groupId>org.projectnessie</groupId>
>       <artifactId>nessie-versioned-jgit</artifactId>
> ```

it's on purpose that we do not depend on a specific implementation


<!-- Sent from Reviewable.io -->

2021-02-09 07:49 UTC, rymurr commented
I am on the fence @laurentgo and @jacques-n, the reason being the `TableMetaStoreWorker` and associated proto def'n are definitely not part of the `quarkus-server`. Any service needs them to function regardless of the underlying server protocol. However the correct place for them to live is up for discussion:
1) in the version store module. I think this is incorrect as the version store module uses only parameterised types
2) services module. This is the first place that the `VerionStore` is specialized to `Contents` and `CommitMeta` so in some ways its not a bad place for them to live
3) new module that services depends on. I am ok with this too but its a whole new module for a class and a protobuf definition
4) in the quarkus-server. As I said this is too high, we have already specialised the `VersionStore` in `services` and the services are useless w/o the store worker and protobuf definition
5) somewhere else?

Having said that the services and quarkus-server modules are still tightly coupled and I am not sure if we should take a crack at decoupling them instead of just shifting 1 class.

2021-02-09 07:53 UTC, rymurr requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @brunos-bq and @laurentgo)

___
*[servers/services/pom.xml, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT3Vggq6N-JGPJoA8_U:-MT4l3JAA_YE8AYODfFt:btmwgaw) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/pom.xml#L40)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

it's on purpose that we do not depend on a specific implementation
</blockquote></details>

agreed, jgit shouldn't be a dependency
___
*[servers/services/src/main/java/com/dremio/nessie/services/rest/TreeResource.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lKGS2_pKM1p3Tstu:-MT4lKGS2_pKM1p3Tstv:be9kkbk) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/java/com/dremio/nessie/services/rest/TreeResource.java#L72)):*
> ```Java
> 
>   @Inject
>   public TreeResource(ServerConfig config, Principal principal,
> ```

why does this need changing?
___
*[servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java, line 16 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lphx8lDA5Md9jzW5:-MT4lphx8lDA5Md9jzW6:b-ytfyaq) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java#L16)):*
> ```Java
>  * limitations under the License.
>  */
> package com.dremio.nessie.services.providers;
> ```

I don't think this is a provider
___
*[servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java, line 56 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4latd7EOxOCnh_jxl:-MT4latd7EOxOCnh_jxm:b-bgh0lg) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java#L56)):*
> ```Java
> import com.google.protobuf.UnsafeByteOperations;
> 
> @Singleton
> ```

I am not 100% convinced that this class should be annotated w/ injection. I think a builder in the specific server modules should take care of it.
___
*[servers/services/src/main/proto/table.proto, line 19 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lBfq4gBAgMJuhruE:-MT4lBfq4gBAgMJuhruF:b1yjt5n) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/proto/table.proto#L19)):*
> ```protobuf
> package com.dremio.plugin.partsyn;
> 
> option java_package = "com.dremio.nessie.jgit";
> ```

I think this package name is wrong, and has been for some time. These don't have any relation to `jgit`


<!-- Sent from Reviewable.io -->

2021-02-09 07:58 UTC, rymurr commented
After thinking more I am actually leaning towards point 3 in my list. A new module that contains workers and utils for the server modules. I think a server doesn't necessarily have to use the Store Worker we use with quarkus but its certainly the easiest option.

2021-02-09 11:02 UTC, snazy commented
+1 on a new `nessie-server` module and move the non-runtime-environment-specific and non-(version-)store-specific code there. (This is related to #786 .) Such a `nessie-server` module must however not depend on any (version-)store configuration or implementation. To build a working Nessie Server, you need three things:
1. Runtime environment (Quarkus or embedded) + code/config specific for the runtime-environment
2. `nessie-server` module
3. One version-store implementation

2021-02-09 19:52 UTC, brunos-bq commented
I have just updated the PR according to all the feedback received.

2021-02-09 20:10 UTC, brunos-bq reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[servers/services/pom.xml, line 40 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT3Vggq6N-JGPJoA8_U:-MT7P41-6tde2CjbBKOm:bm9eeu5) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/pom.xml#L40)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

agreed, jgit shouldn't be a dependency
</blockquote></details>

The dependency was not needed and removed.
___
*[servers/services/src/main/java/com/dremio/nessie/services/rest/TreeResource.java, line 72 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lKGS2_pKM1p3Tstu:-MT7P8Tf6dRqv3NHf4vW:bloiygd) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/java/com/dremio/nessie/services/rest/TreeResource.java#L72)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

why does this need changing?
</blockquote></details>

The way we instantiate a VersionStore where Nessie will be embedded, we use build the TreeResource object using this constructor.
___
*[servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java, line 16 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lphx8lDA5Md9jzW5:-MT7OsVu3xlEcBy-Neja:bt2vr1b) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java#L16)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I don't think this is a provider
</blockquote></details>

Fixed.
___
*[servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java, line 56 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4latd7EOxOCnh_jxl:-MT7PSrw5mtVYIQTXJvm:bxexult) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/java/com/dremio/nessie/services/providers/TableCommitMetaStoreWorker.java#L56)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I am not 100% convinced that this class should be annotated w/ injection. I think a builder in the specific server modules should take care of it.
</blockquote></details>

Should this be done in this PR, or as a TODO?
___
*[servers/services/src/main/proto/table.proto, line 19 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lBfq4gBAgMJuhruE:-MT7P-Vu0FpHZKKDGjqo:byyojxv) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/proto/table.proto#L19)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I think this package name is wrong, and has been for some time. These don't have any relation to `jgit`
</blockquote></details>

Not familiar with this part of the code. What would be a good replacement name?


<!-- Sent from Reviewable.io -->

2021-02-10 11:55 UTC, rymurr reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @brunos-bq, @laurentgo, and @rymurr)

___
*[servers/services/src/main/proto/table.proto, line 19 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lBfq4gBAgMJuhruE:-MTAm2p33XbUrHhSDhsc:buxok4u) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/proto/table.proto#L19)):*
<details><summary><i>Previously, brunos-bq (Bruno Paiva Lima da Silva) wrote…</i></summary><blockquote>

Not familiar with this part of the code. What would be a good replacement name?
</blockquote></details>

`com.dremio.nessie.server.model`?


<!-- Sent from Reviewable.io -->

2021-02-10 11:58 UTC, rymurr commented on servers/server/pom.xml
> +    <dependency>
these jboss and javax/jakarta dependencies look strange to me. Where are the coming from?

2021-02-10 12:03 UTC, rymurr commented
I am happier with this in another module. @snazy  @laurentgo @jacques-n ? Thoughts?

This still isn't ideal and it feels squishy to me but I don't have a better way atm. This module is better than forcing everyone who may want to implement a server to pull in quarkus stuff. Short of other servers creating their own workers, which given the size of the Worker may actually be better. There is no reason that all servers should be forced to use protobuf to store values.

2021-02-10 18:55 UTC, brunos-bq reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[servers/server/pom.xml, line 55 at r2](https://reviewable.io/reviews/projectnessie/nessie/783#-MT7KWr839oPi-e9mZgt-r2-55:-MTCHuQf-QIi5Jgn2v15:bhv09xr) ([raw file](https://github.com/projectnessie/nessie/blob/19289c96e62baf5e3c9ad8f3be3844d0f82eb12f/servers/server/pom.xml#L55)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

these jboss and javax/jakarta dependencies look strange to me. Where are the coming from?
</blockquote></details>

Some dependencies were not needed. Removed them.
___
*[servers/services/src/main/proto/table.proto, line 19 at r1](https://reviewable.io/reviews/projectnessie/nessie/783#-MT4lBfq4gBAgMJuhruE:-MTCI-yS2AvXg_i_y5_F:b-h1kwns) ([raw file](https://github.com/projectnessie/nessie/blob/fd5ffae247c48adfcf3d24489dac6a9f32c91209/servers/services/src/main/proto/table.proto#L19)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

`com.dremio.nessie.server.model`?
</blockquote></details>

That works. Updating.


<!-- Sent from Reviewable.io -->

2021-02-10 18:58 UTC, brunos-bq commented
r3: Removed unused dependencies. Renamed package hierarchy in table.proto.

2021-02-11 05:15 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @brunos-bq, @laurentgo, and @rymurr)

___
*[servers/server/src/main/proto/table.proto, line 17 at r3](https://reviewable.io/reviews/projectnessie/nessie/783#-MTEV_N10rjR7xnGo2RL:-MTEV_N10rjR7xnGo2RM:b7z1p6g) ([raw file](https://github.com/projectnessie/nessie/blob/34bb8a4fb2d8879ec34382cd35326beec52a6680/servers/server/src/main/proto/table.proto#L17)):*
> ```protobuf
>  */
> syntax = "proto3";
> package com.dremio.plugin.partsyn;
> ```

this is definitely wrong too :)


<!-- Sent from Reviewable.io -->

2021-02-11 05:18 UTC, laurentgo commented
> This still isn't ideal and it feels squishy to me but I don't have a better way atm. This module is better than forcing everyone who may want to implement a server to pull in quarkus stuff. Short of other servers creating their own workers, which given the size of the Worker may actually be better. There is no reason that all servers should be forced to use protobuf to store values.

The main question for me seems to be "Do we need a different implementation of StoreWorker?". One area for sure which is not great at the moment is the mapping requirement between a POJO in model and a Protobuf class in the store worker. This doesn't seem something extensible and working well especially if multiple store worker implementions have to be supported.

2021-02-11 23:01 UTC, brunos-bq reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/783)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[servers/server/src/main/proto/table.proto, line 17 at r3](https://reviewable.io/reviews/projectnessie/nessie/783#-MTEV_N10rjR7xnGo2RL:-MTIJz9KApG4DCbeTmpE:bt2vr1b) ([raw file](https://github.com/projectnessie/nessie/blob/34bb8a4fb2d8879ec34382cd35326beec52a6680/servers/server/src/main/proto/table.proto#L17)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

this is definitely wrong too :)
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-03-04 09:25 UTC, rymurr commented
closing as this was done in #895

2021-03-04 09:25 UTC, closed without merging