Respect DynamoDB limit of max 25 requests per batch-write
projectnessie/nessie pull request #798
Opened 2021-02-10 16:12 UTC by snazy

While running some perf-test experiments, I ran into situations that DynamoDB refused a Batch-Write for a `save()` due to exceeded limits. The current implementation of `com.dremio.nessie.versioned.store.dynamo.DynamoStore#save` does some already some grouping, but it was incorrect and used a way too high limit (100).

The [DynamoDB BatchWriteItem docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) says, that all batch-writes with more than 25 requests will be rejected.

I'm not sure, why the existing `DynamoStore.save()` implementation used the `paginationSize` (defaults to  `LOAD_SIZE`, defaults to `100`), so I left it there, but limited the number of requests to 25.

I don't _think_ that we need to assert on a single request being > 400kB or the whole batch > 16MB, because IIRC Nessie objects are already "capped" at 400kB and 25*400 is not > 16MB.

2021-02-10 17:35 UTC, rymurr submitted a review, later dismissed

2021-02-10 17:56 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/798)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @snazy)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 114 at r1](https://reviewable.io/reviews/projectnessie/nessie/798#-MTC39kQ3Qhj3GeS81Ad:-MTC39kQ3Qhj3GeS81Ae:bgmf5bv) ([raw file](https://github.com/projectnessie/nessie/blob/e95f1d826c402a4c02f0c57ea30e8b288241b023/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L114)):*
> ```Java
>    * state a batch-write be rejected, if it contains more than 25 requests in a batch.
>    */
>   public static final int DYNAMO_BATCH_WRITE_LIMIT_COUNT = 25;
> ```

isn't that some internal concern?
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 357 at r1](https://reviewable.io/reviews/projectnessie/nessie/798#-MTC41W4AxSEzHimAvOK:-MTC41W4AxSEzHimAvOL:be988zc) ([raw file](https://github.com/projectnessie/nessie/blob/e95f1d826c402a4c02f0c57ea30e8b288241b023/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L357)):*
> ```Java
>     // The following nested forEach construct collects up to `pageSize` `WriteRequest`s in
>     // the `currentBatch` map. The current number of `WriteRequest`s is held in `currentBatchSize[0]`.
>     Map<String, Collection<WriteRequest>> currentBatch = new HashMap<>();
> ```

isn't that a good use case for a collector which could handle the batching and processing?

Or maybe we should look at using reacting stream like we did for Mongo?


<!-- Sent from Reviewable.io -->

2021-02-11 18:30 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/798)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @laurentgo)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 114 at r1](https://reviewable.io/reviews/projectnessie/nessie/798#-MTC39kQ3Qhj3GeS81Ad:-MTHL0II8nD9JjenMvmt:bwjcd2l) ([raw file](https://github.com/projectnessie/nessie/blob/e95f1d826c402a4c02f0c57ea30e8b288241b023/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L114)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

isn't that some internal concern?
</blockquote></details>

Made it package-private
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 357 at r1](https://reviewable.io/reviews/projectnessie/nessie/798#-MTC41W4AxSEzHimAvOK:-MTHL5TS9TBUNcLHcC48:b-97knep) ([raw file](https://github.com/projectnessie/nessie/blob/e95f1d826c402a4c02f0c57ea30e8b288241b023/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L357)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

isn't that a good use case for a collector which could handle the batching and processing?

Or maybe we should look at using reacting stream like we did for Mongo?
</blockquote></details>

`Collector` are quite difficult to use here due to the, say, "batching characteristics" here. Not so happy with pulling in a reflective-stuff-library to do this.
I opted to extract the "collecting magic" into a separate class, which is package-private, because it's implementation pretty focused on how the Dynamo-Java-API requires the batches to work.

Since that class is actually pretty isolated, I'll add a unit test for it as well in a few.


<!-- Sent from Reviewable.io -->

2021-02-12 09:34 UTC, rymurr reviewed
just the class rename and the rebase missing. I think the code is a lot easier to read w/ the change to a separate class

2021-02-12 09:34 UTC, rymurr commented on versioned/tiered/dynamodb/src/test/java/com/dremio/nessie/versioned/store/dynamo/BatchesCollectorTest.java
> +public class BatchesCollectorTest {
all other tests have Test* format

2021-02-12 10:34 UTC, rymurr approved these changes

2021-02-12 12:17 UTC, snazy reviewed
> Dismissed @laurentgo from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/798)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @snazy)

___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 114 at r1](https://reviewable.io/reviews/projectnessie/nessie/798#-MTC39kQ3Qhj3GeS81Ad:-MTLA4do2IR_pVOvBVq0:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e95f1d826c402a4c02f0c57ea30e8b288241b023/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L114)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Made it package-private
</blockquote></details>

Done.
___
*[versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java, line 357 at r1](https://reviewable.io/reviews/projectnessie/nessie/798#-MTC41W4AxSEzHimAvOK:-MTLA1J9-cOMVpO80rNY:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e95f1d826c402a4c02f0c57ea30e8b288241b023/versioned/tiered/dynamodb/src/main/java/com/dremio/nessie/versioned/store/dynamo/DynamoStore.java#L357)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

`Collector` are quite difficult to use here due to the, say, "batching characteristics" here. Not so happy with pulling in a reflective-stuff-library to do this.
I opted to extract the "collecting magic" into a separate class, which is package-private, because it's implementation pretty focused on how the Dynamo-Java-API requires the batches to work.

Since that class is actually pretty isolated, I'll add a unit test for it as well in a few.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-12 12:18 UTC, merged