Add RandomSource utility class
projectnessie/nessie pull request #862
Opened 2021-02-23 16:03 UTC by laurentgo

In order for some unit tests to be repeteable, it is required to be able
to set the seed for the random generator used by the source.

Currently it requires code to accept a Random instance argument with the
test framework to set the seed before hand, but this approach makes code
heavier (the Random instance needs to be passed between function calls)
for what should is usually an internal concern.

Replace this pattern with a new utility class named `RandomSource` which
behave exactly like `ThreadLocalRandom` except that it is possible to
temporarily override the current random generator with one initialized
with a specific seed.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/projectnessie/nessie/862)

2021-02-24 08:04 UTC, rymurr reviewed
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/862)* status: all files reviewed, 3 unresolved discussions (waiting on @laurentgo)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI3Jjg--OW3nyiGCBU:-MUI3Jjg--OW3nyiGCBV:bukaxfd) (no related file):*
LGTM, a few comments for clarification.

---
___
*[utils/src/main/java/org/projectnessie/RandomSource.java, line 36 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI1KHz5jWq2OASSzNA:-MUI1KHz5jWq2OASSzNB:bh3w2ql) ([raw file](https://github.com/projectnessie/nessie/blob/a7fd974fd451bcb7210ef4e1e18ad1967cca9972/utils/src/main/java/org/projectnessie/RandomSource.java#L36)):*
> ```Java
>   private static final RandomSource INSTANCE = new RandomSource();
> 
>   private final boolean isInitialized;
> ```

this seems weird. Maybe its just a part of java i dont understand though. To me this field is always true and never used
___
*[versioned/tiered/tiered-tests/src/main/java/org/projectnessie/versioned/impl/AbstractTestStore.java, line 116 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI3-qBD5JRvlJ7cP9J:-MUI3-qBD5JRvlJ7cP9K:b-lv0sb3) ([raw file](https://github.com/projectnessie/nessie/blob/aaccb0ba6799c319759a924c323556ac2317b123/versioned/tiered/tiered-tests/src/main/java/org/projectnessie/versioned/impl/AbstractTestStore.java#L116)):*
> ```Java
>   protected abstract S createRawStore();
> 
>   protected abstract long getRandomSeed();
> ```

does this mean we made every impl set a random seed, they all set it the same and it wasn't required?


<!-- Sent from Reviewable.io -->

2021-02-24 10:28 UTC, snazy requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/862)* status: all files reviewed, 4 unresolved discussions (waiting on @laurentgo and @rymurr)

*[a discussion](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI3Jjg--OW3nyiGCBU:-MUIWhcbBcn2mBAPhp8K:b-auopdc) (no related file):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

LGTM, a few comments for clarification.
</blockquote></details>

I'd favor a slightly different annotation/JUnit-extension that auto-magically sets up a `RandomSource` with an optional seed. I.e. instead of having a `@WithSeed` annotation, have an annotation `@WithRandom` that optionally takes a seed value and falls back to a random seed value.

To make tests reproducible, it would be necessary to somehow print the seed value of a failed test run, as you need to know that seed value to reproduce the test failure. To (quickly) re-run a test with a known seed value, it feels easier to specify the seed-value as a system property.

Not sure why some tests already specify a constant seed-value. Why do we specify constant seed-values at all?

Can you add some tests for the JUnit extension?

---
___
*[utils/pom.xml, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUIND9A-rgRITSUOAU1:-MUIND9A-rgRITSUOAU2:b-hej36y) ([raw file](https://github.com/projectnessie/nessie/blob/a7fd974fd451bcb7210ef4e1e18ad1967cca9972/utils/pom.xml#L28)):*
> ```XML
>   </parent>
> 
>   <artifactId>nessie-utils</artifactId>
> ```

Can you rename this module to `nessie-test-utils`?
___
*[utils/src/main/java/org/projectnessie/RandomSource.java, line 36 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI1KHz5jWq2OASSzNA:-MUIOqzb0j7P7JsOkNVx:bpxlnbz) ([raw file](https://github.com/projectnessie/nessie/blob/a7fd974fd451bcb7210ef4e1e18ad1967cca9972/utils/src/main/java/org/projectnessie/RandomSource.java#L36)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this seems weird. Maybe its just a part of java i dont understand though. To me this field is always true and never used
</blockquote></details>

Def. needs some inline-docs, but the default `Random` constructor is called before `RandomSource`'s constructor's being executed. `Random`'s constructor calls `setSeed`.


<!-- Sent from Reviewable.io -->

2021-02-24 19:37 UTC, laurentgo reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/862)* status: all files reviewed, 4 unresolved discussions (waiting on @rymurr and @snazy)

___
*[utils/pom.xml, line 28 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUIND9A-rgRITSUOAU1:-MUKVfAY0NmDY07NwVAH:b-2bq9mx) ([raw file](https://github.com/projectnessie/nessie/blob/a7fd974fd451bcb7210ef4e1e18ad1967cca9972/utils/pom.xml#L28)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Can you rename this module to `nessie-test-utils`?
</blockquote></details>

I would prefer not as `RandomSource` is used outside of test contexts...
___
*[utils/src/main/java/org/projectnessie/RandomSource.java, line 36 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI1KHz5jWq2OASSzNA:-MUKVomI84bfSpY0N2lF:b-cycud6) ([raw file](https://github.com/projectnessie/nessie/blob/a7fd974fd451bcb7210ef4e1e18ad1967cca9972/utils/src/main/java/org/projectnessie/RandomSource.java#L36)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Def. needs some inline-docs, but the default `Random` constructor is called before `RandomSource`'s constructor's being executed. `Random`'s constructor calls `setSeed`.
</blockquote></details>

This is because `Random` base class is weird: base constructor will call `setSeed`, so the call should not fail until the flag is set to `true` which cause later calls to `setSeed` to throw `UOE`.
___
*[versioned/tiered/tiered-tests/src/main/java/org/projectnessie/versioned/impl/AbstractTestStore.java, line 116 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI3-qBD5JRvlJ7cP9J:-MUKWE_cAXzBILlVbCm8:b-jx7kz) ([raw file](https://github.com/projectnessie/nessie/blob/aaccb0ba6799c319759a924c323556ac2317b123/versioned/tiered/tiered-tests/src/main/java/org/projectnessie/versioned/impl/AbstractTestStore.java#L116)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

does this mean we made every impl set a random seed, they all set it the same and it wasn't required?
</blockquote></details>

not sure what you comment is referencing tbh...


<!-- Sent from Reviewable.io -->

2021-02-25 08:29 UTC, rymurr requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/862)* status: all files reviewed, 4 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[utils/src/main/java/org/projectnessie/RandomSource.java, line 36 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI1KHz5jWq2OASSzNA:-MUNIV9wAA_ypWMPKDHR:btvsxud) ([raw file](https://github.com/projectnessie/nessie/blob/a7fd974fd451bcb7210ef4e1e18ad1967cca9972/utils/src/main/java/org/projectnessie/RandomSource.java#L36)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

This is because `Random` base class is weird: base constructor will call `setSeed`, so the call should not fail until the flag is set to `true` which cause later calls to `setSeed` to throw `UOE`.
</blockquote></details>

Can we just add that to the javadoc or stick a comment in somewhere?
___
*[versioned/tiered/tiered-tests/src/main/java/org/projectnessie/versioned/impl/AbstractTestStore.java, line 116 at r1](https://reviewable.io/reviews/projectnessie/nessie/862#-MUI3-qBD5JRvlJ7cP9J:-MUNIbVh3e0tAibnkWda:b-7tk5zm) ([raw file](https://github.com/projectnessie/nessie/blob/aaccb0ba6799c319759a924c323556ac2317b123/versioned/tiered/tiered-tests/src/main/java/org/projectnessie/versioned/impl/AbstractTestStore.java#L116)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

not sure what you comment is referencing tbh...
</blockquote></details>

nws, will discuss offline


<!-- Sent from Reviewable.io -->

2022-01-19 14:32 UTC, rymurr commented
closing as significantly out of date

2022-01-19 14:32 UTC, closed without merging