Pimp perf-test-stuff
projectnessie/nessie pull request #940
Opened 2021-03-11 15:20 UTC by snazy

Make `perftest/` a Maven parent pom, remove the JMeter test, add "management-pack", add Gatling-test

Some readmes are there:
* https://github.com/snazy/nessie/blob/perf-test-stuff/perftest/README.md
* https://github.com/snazy/nessie/tree/perf-test-stuff/perftest/measurement-pack
* https://github.com/snazy/nessie/tree/perf-test-stuff/perftest/gatling

2021-03-11 15:34 UTC, snazy commented
Oh, apologies. I didn't knew that it is offensive. Sorry!

2021-03-15 12:25 UTC, rymurr requested changes
> Reviewed 33 of 34 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/940)* status: all files reviewed, 19 unresolved discussions (waiting on @snazy)

___
*[perftest/README.md, line 5 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpgJ-4-1buBgh-3K2N:-MVpgJ-4-1buBgh-3K2O:bvyzuea) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L5)):*
> some more

some more what?
___
*[perftest/README.md, line 25 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpgfO72UhcFdcZz8S1:-MVpgfO72UhcFdcZz8S2:btspuup) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L25)):*
> ```Markdown
>   (Install [docker compose](https://docs.docker.com/compose/install/))
> 1. Build & Start Nessie
>   ```shell
> ```

I think this would be better as part of the docker compose. Especially as the benchmark is then run against a prod server instance
___
*[perftest/README.md, line 65 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVphhWXCj9UizKGaSsb:-MVphhWYALa7mxl72Hkv:b-mw5bor) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L65)):*
> ```Markdown
> 1. Play around & run more tests
> 
> ## Example against AWS / EC2 / DynamoDB
> ```

Can we put the EC2 stuff in a separate doc or hidden in a subfolder. I don't think hand formatting NVMe drives and docker is something I want normal people doing and its not overly reproducible. We can add some cloud fomration templates or equivalent later to 'productionise'  the load test.

Broadly the EC2 part of this doc is part personal notes, part script and part docs. I think removing some of the notes and turning this into more of a script would be good. However most of it could be replaced by automation tools so maybe we should just hide it for now?
___
*[perftest/README.md, line 201 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpiblG7h0sPbYm4_iF:-MVpiblG7h0sPbYm4_iG:b-861xit) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L201)):*
> ```Markdown
> 
> # Clone Nessie (this is from my personal branch!)
> git clone -o snazy -b trace-commit https://github.com/snazy/nessie.git nessie
> ```

this should prob change
___
*[perftest/README.md, line 312 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpj4Lv3KVDxpugrvBD:-MVpj4Lv3KVDxpugrvBE:b-5k2lr7) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L312)):*
> ```Markdown
> chmod -R o+w prometheus-data
> docker-compose up
> xdg-open http://127.0.0.1:3000/
> ```

not many people are going to be doing this from linux. 
___
*[perftest/README.md, line 320 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpjJMh77bGvvB00NFf:-MVpjJMh77bGvvB00NFg:bvxp52e) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L320)):*
> ```Markdown
> 
> ```shell
> aws iam create-user --user-name nessie-perftest
> ```

I feel like creating a user is a bit heavy handed and not great practice. I would prefer to remove this and jsut specify the rights required or the IAM policy required to run the test.
___
*[perftest/README.md, line 335 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpjkMS6bTSVCBJLnNT:-MVpjkMS6bTSVCBJLnNU:bbmocdl) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L335)):*
> ```Markdown
> ## ssh into the EC2 instance
> 
> ```
> ```

either some explanation of this or remove it. I don't think a lot of people know what this does. 
___
*[perftest/gatling/pom.xml, line 83 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkPsp0uwlhXhXZ1qV:-MVpkPsp0uwlhXhXZ1qW:b-385oz8) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/pom.xml#L83)):*
> ```XML
>       <groupId>io.prometheus</groupId>
>       <artifactId>simpleclient_pushgateway</artifactId>
>       <version>0.10.0</version>
> ```

move to parent pom?
___
*[perftest/gatling/README.md, line 6 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkbnEDsC7J6RVoGzT:-MVpkbnEDsC7J6RVoGzU:b-r5smny) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L6)):*
> ```Markdown
> 
> 1. Follow the instructions in `perftest/measurement-pack/README.md` to start the measurement-pack
> 1. Build Nessie: go to the Nessie root directory and execute `./mvnw clean install`, activate the
> ```

As previous I think first port of call should be `projectnessie/nessie:latest`
___
*[perftest/gatling/README.md, line 37 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkq5Q1C7u2kbXNTGp:-MVpkq5Q1C7u2kbXNTGq:b-cuqpk3) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L37)):*
> ```Markdown
> ```
> 
> To start a Nessie native-image, replace the part above starting with the `java` executable with `servers/quarkus-server/target/nessie-quarkus-*-SNAPSHOT-runner`
> ```

Better to re-write the whole command. People will typically be copy-pasting.
___
*[perftest/gatling/README.md, line 49 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpl0tV1_7R_5qQC6q2:-MVpl0tV1_7R_5qQC6q3:bpkl961) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L49)):*
> ```Markdown
> 
> # Run the Gatling test  (parameter values represent the default values)
> #   sim.users               -> number of users to simulate
> ```

I think it would be good to expand this into a markdown table. This is the key part of this readme and i didn't see it at first. Also maybe some example simulations and what they mean/how to interpret them?
___
*[perftest/gatling/src/main/scala/org/projectnessie/perftest/gatling/NessieProtocol.scala, line 99 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpmUFq0KgmOXX0h5Ly:-MVpmUFq0KgmOXX0h5Lz:b-o42lom) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/src/main/scala/org/projectnessie/perftest/gatling/NessieProtocol.scala#L99)):*
> ```Scala
>   private val metricsInfo = new AtomicReference[MetricsInfo]()
> 
>   def start(push: PrometheusPush, session: Session): Session = this.synchronized {
> ```

is it easier to use a plugin? https://github.com/bmaguireibm/gatling-prometheus-datawriter
___
*[perftest/measurement-pack/docker-compose.yml, line 84 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpmr7O7ZsDai0W-GG9:-MVpmr7O7ZsDai0W-GGA:b-x4182s) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/measurement-pack/docker-compose.yml#L84)):*
> ```YAML
>   # This container is needed to let e.g. Prometheus scrape the metrics from the Nessie server
>   # running on the Docker host (your machine). Make sure, your firewall doesn't block that traffic.
>   docker-host:
> ```

this is error prone and not required if we put the nessie image into the docker compose
___
*[perftest/measurement-pack/configs/grafana/grafana.ini, line 355 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpniLx6unrrIgRYe-b:-MVpniLx6unrrIgRYe-c:b-7ngkno) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/measurement-pack/configs/grafana/grafana.ini#L355)):*
> ```INI
> [auth.anonymous]
> # enable anonymous access
> enabled = true
> ```

sad face
___
*[perftest/measurement-pack/configs/grafana/dashboards/Nessie.json, line 2 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpoJ2M [...]

2021-03-15 12:29 UTC, rymurr commented
A minor note, I find the gatling code as opaque and long as the jmeter xml.  Maybe some more comments would help? What are the advantages over the ~150 line jmx file?

2021-03-16 10:15 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/940)* status: all files reviewed, 19 unresolved discussions (waiting on @rymurr)

___
*[perftest/README.md, line 5 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpgJ-4-1buBgh-3K2N:-MVuRU5ZB80Os5ykWHvj:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L5)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

> some more

some more what?
</blockquote></details>

Done.
___
*[perftest/README.md, line 25 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpgfO72UhcFdcZz8S1:-MVuRUzq0qEM9MXiCkqH:b-c2pm1n) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L25)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I think this would be better as part of the docker compose. Especially as the benchmark is then run against a prod server instance
</blockquote></details>

Actually no. It is much easier to test code changes and also debug Nessie server + Gatling tests and to apply various confiurations.
We do not have a production-ready server yet. It is not a big deal to add another Docker-Compose config later that uses a Nessie-Docker-container, but for now I'd really like to keep it separate.
___
*[perftest/README.md, line 65 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVphhWXCj9UizKGaSsb:-MVuSp7m3dLfWcLGvTDK:b-2mvrbq) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L65)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Can we put the EC2 stuff in a separate doc or hidden in a subfolder. I don't think hand formatting NVMe drives and docker is something I want normal people doing and its not overly reproducible. We can add some cloud fomration templates or equivalent later to 'productionise'  the load test.

Broadly the EC2 part of this doc is part personal notes, part script and part docs. I think removing some of the notes and turning this into more of a script would be good. However most of it could be replaced by automation tools so maybe we should just hide it for now?
</blockquote></details>

Moved the stuff to a separate folder, so we can look it up later - don't want to lose the information at the moment. Once everything's in a much more stable state, we can certainly add automation stuff.
___
*[perftest/README.md, line 201 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpiblG7h0sPbYm4_iF:-MVuT4K91DLhbHlMUMo_:b-bu91xm) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L201)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this should prob change
</blockquote></details>

Updated
___
*[perftest/README.md, line 312 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpj4Lv3KVDxpugrvBD:-MVuT9sg8JsWcYtRl7Ji:bs6vsz5) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L312)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

not many people are going to be doing this from linux. 
</blockquote></details>

Added an `if`
___
*[perftest/README.md, line 320 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpjJMh77bGvvB00NFf:-MVuTCPBBjWULAoJgbpT:b-o8ofmw) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L320)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I feel like creating a user is a bit heavy handed and not great practice. I would prefer to remove this and jsut specify the rights required or the IAM policy required to run the test.
</blockquote></details>

Moved to the "script notes" folder
___
*[perftest/README.md, line 335 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpjkMS6bTSVCBJLnNT:-MVuTGSd1Nn3zYeuJbom:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L335)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

either some explanation of this or remove it. I don't think a lot of people know what this does. 
</blockquote></details>

Done.
___
*[perftest/gatling/pom.xml, line 83 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkPsp0uwlhXhXZ1qV:-MVuTHVT9CKc3mJqliqH:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/pom.xml#L83)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

move to parent pom?
</blockquote></details>

Done.
___
*[perftest/gatling/README.md, line 6 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkbnEDsC7J6RVoGzT:-MVuTIMj6UfOOO0BY7P0:bbrfz13) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L6)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

As previous I think first port of call should be `projectnessie/nessie:latest`
</blockquote></details>

It's actually error prone and more effort IMO - and definitely more effort when you investigate issues. The goal of the perf-testing-infra for now is to have something that works and allows to easily try out changes to both code and config and running both Nessie server and Gatling tests in a debugger.
___
*[perftest/gatling/README.md, line 37 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkq5Q1C7u2kbXNTGp:-MVuVcI43MNZS-NkdJsC:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L37)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

Better to re-write the whole command. People will typically be copy-pasting.
</blockquote></details>

Done.
___
*[perftest/gatling/README.md, line 49 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpl0tV1_7R_5qQC6q2:-MVuVdTsEOyv6GjMaDBD:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L49)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

I think it would be good to expand this into a markdown table. This is the key part of this readme and i didn't see it at first. Also maybe some example simulations and what they mean/how to interpret them?
</blockquote></details>

Done.
___
*[perftest/gatling/src/main/scala/org/projectnessie/perftest/gatling/NessieProtocol.scala, line 99 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpmUFq0KgmOXX0h5Ly:-MVuVeVO7vZP3qGL_e5T:b-4a1hit) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/src/main/scala/org/projectnessie/perftest/gatling/NessieProtocol.scala#L99)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

is it easier to use a plugin? https://github.com/bmaguireibm/gatling-prometheus-datawriter
</blockquote></details>

Nope, that plugin scrapes, but doesn't support the Push Gateway
___
*[perftest/measurement-pack/docker-compose.yml, line 84 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpmr7O7ZsDai0W-GG9:-MVuVnUo1Ufozm2pUkh6:b-eozsw9) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/measurement-pack/docker-compose.yml#L84)):*
<details><summary><i>Previously, rymurr (Ryan Murray) wrote…</i></summary><blockquote>

this is error prone and not required if we put the nessie  [...]

2021-03-18 05:19 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/940)* status: 23 of 33 files reviewed, 28 unresolved discussions (waiting on @rymurr and @snazy)

___
*[pom.xml, line 133 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2iI_YBtaVRCIeG1TX:-MW2iI_YBtaVRCIeG1TY:b4kfovq) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/pom.xml#L133)):*
> ```XML
>     <jackson.version>2.12.1</jackson.version>
>     <javax.version>4.0.1</javax.version>
>     <jaeger.version>1.3.2</jaeger.version>
> ```

that's actually not the most recent version of jaeger. Any idea why?
___
*[perftest/README.md, line 25 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpgfO72UhcFdcZz8S1:-MW2d6Mq1J91XfILZv3L:blf3qtr) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L25)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Actually no. It is much easier to test code changes and also debug Nessie server + Gatling tests and to apply various confiurations.
We do not have a production-ready server yet. It is not a big deal to add another Docker-Compose config later that uses a Nessie-Docker-container, but for now I'd really like to keep it separate.
</blockquote></details>

On the other hand, I'm not sure I'd trust results on things running locally with the loader on the same machine as Nessie which the instructions seems to suggest. Also this uses the Java runner, but not the native image which is easily produced by Quarkus (and I thought we were targeting the native image for performance numbers)
___
*[perftest/README.md, line 104 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2eDXBCj4v3ZQ6uRtf:-MW2eDXCA4PNivjHhHGc:beag0b1) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/README.md#L104)):*
> ```Markdown
> ##############################
> 
> ./mvnw install gatling:test -Dgatling.simulationClass=org.projectnessie.perftest.gatling.CommitToBranchSimulation \
> ```

cannot the simulation class be part of the gatling configuration in that module?
___
*[perftest/ec2-sample-scripts/aws-iam-notes.in.sh, line 17 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2ekm6EzT-y_i7nAnZ:-MW2ekm6EzT-y_i7nAn_:b10f8xe) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/ec2-sample-scripts/aws-iam-notes.in.sh#L17)):*
> ```Shell
> #
> 
> ## THIS IS NOT A SCRIPT THAT CAN BE BLINDLY EXECUTED!
> ```

should it be a script or a markdown document? even not blindly executed, the script is weird: I'm not sure what the group is for tbh, and if you already have enough access to create IAM users and access key, you should probably be able to use it for Nessie too (especially considering there's no IAM policy attached to the user).
___
*[perftest/gatling/pom.xml, line 64 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2iSAj2f8v2H2nh3FK:-MW2iSAj2f8v2H2nh3FL:b-n4xjbx) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/pom.xml#L64)):*
> ```XML
>       <artifactId>jaeger-thrift</artifactId>
>       <exclusions>
>         <!-- jaeger-thrift 3.43.3 pulls in a banned version of annotation-api. Remove once we move to jaeger 1.x-->
> ```

I guess you meant 0.34.3? (it took me a while to figure this out)

Note that there's a jaeger.version property defined at the top level, but it is not used here, so the version is basically whatever is imported by Quarkus I would guess? that said, 0.34.3 is fairly old (a year old), and I wonder why Quarkus hasn't updated, and if there would be some issues if forcing a newer version (but it might not be possible sadly: https://github.com/quarkusio/quarkus/issues/5907)
___
*[perftest/gatling/pom.xml, line 119 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2hsY85tkEqcn4DNkI:-MW2hsY85tkEqcn4DNkJ:b-f5h9ai) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/pom.xml#L119)):*
> ```XML
>         <groupId>io.gatling</groupId>
>         <artifactId>gatling-maven-plugin</artifactId>
>         <version>${gatling.maven.version}</version>
> ```

let's move it under pluginManagement? (like it was done for jmeter?)
___
*[perftest/gatling/README.md, line 6 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkbnEDsC7J6RVoGzT:-MW2hHPO-_aIc6eVO-ap:bbsc7yq) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L6)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

It's actually error prone and more effort IMO - and definitely more effort when you investigate issues. The goal of the perf-testing-infra for now is to have something that works and allows to easily try out changes to both code and config and running both Nessie server and Gatling tests in a debugger.
</blockquote></details>

I have a hard visualizing running a performance test with debugger attached and breakpoints tbh. If you investigate issues, it's probably faster to create a unit or integration test to reproduce some behavior observed and run it in a debugger, instead of having a whole performance + telemetry stack waiting while you're debugging?
___
*[perftest/gatling/src/test/scala/Engine.scala, line 20 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2h-p71dYvrnwMD2IY:-MW2h-p71dYvrnwMD2IZ:b-cium0n) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/Engine.scala#L20)):*
> ```Scala
> 
> /**
>  * Class generated by the Maven archetype for Gatling.
> ```

is it important to keep how this class was generated?
___
*[perftest/gatling/src/test/scala/IDEPathHelper.scala, line 19 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2gxjg9Fyw2SJoftT-:-MW2gxjg9Fyw2SJoftT0:b-cium0n) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/IDEPathHelper.scala#L19)):*
> ```Scala
> 
> /**
>  * Class generated by the Maven archetype for Gatling.
> ```

is it important to keep how this class was generated?
___
*[perftest/gatling/src/test/scala/Recorder.scala, line 20 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2gpdv4lOUefzcQ2su:-MW2gpdv4lOUefzcQ2sv:b-cium0n) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/Recorder.scala#L20)):*
> ```Scala
> 
> /**
>  * Class generated by the Maven archetype for Gatling.
> ```

is it important to keep how this class was generated?
___
*[perftest/measurement-pack/docker-compose.yml, line 84 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpmr7O7ZsDai0W-GG9:-MW2gWav-kOAF8z5lDRq:b-kqzst3) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/measurement-pack/docker-compose.yml#L84)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

I'd really like to keep this for now. It is much easier during development and debugging and testing out various configurations.
We can always add another docker-compose.yml later.
</blockquote></details>

Didn't we have those docker-compose.yml already, and they were removed instead of being adjusted for your changes?
___
*[perftest/measurement-pack/pom.xml, line 1 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2gM037bUayh5eHoNJ:-MW2gM037bUayh5eHoNK:b-bz43l9) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/measurement-pack/pom.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

If there's no code, no packagin [...]

2021-03-18 09:54 UTC, snazy reviewed
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/940)* status: 18 of 33 files reviewed, 28 unresolved discussions (waiting on @laurentgo and @rymurr)

___
*[pom.xml, line 133 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2iI_YBtaVRCIeG1TX:-MW3gvwh8WFLe38IddlA:b-kuuf60) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/pom.xml#L133)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

that's actually not the most recent version of jaeger. Any idea why?
</blockquote></details>

It wasn't used at all. Removed it.
___
*[perftest/README.md, line 25 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpgfO72UhcFdcZz8S1:-MW3h-jC6q6VoMormRsf:b-b9vavh) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/README.md#L25)):*
> I'm not sure I'd trust results on things running locally with the loader on the same machine as Nessie

How's this different from the previous jmeter setup? I generally agree that a proper performance test should reflect a real production setup, but that's way more effort but also introduces a lot of unknowns as well. Ideally we'd have a lot of bare-metal machines running in an unshared network.
___
*[perftest/README.md, line 104 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2eDXBCj4v3ZQ6uRtf:-MW3iu-G5qn14D1zkOIb:b-umag7l) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/README.md#L104)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

cannot the simulation class be part of the gatling configuration in that module?
</blockquote></details>

As long as we have just one simulation, yes. Other simulations that perform merges / transplants / GC probably end up in different classes.
___
*[perftest/ec2-sample-scripts/aws-iam-notes.in.sh, line 17 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2ekm6EzT-y_i7nAnZ:-MW3jEDX7qmMUi6pijH0:b-kdkdf4) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/ec2-sample-scripts/aws-iam-notes.in.sh#L17)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

should it be a script or a markdown document? even not blindly executed, the script is weird: I'm not sure what the group is for tbh, and if you already have enough access to create IAM users and access key, you should probably be able to use it for Nessie too (especially considering there's no IAM policy attached to the user).
</blockquote></details>

Removed that file
___
*[perftest/gatling/pom.xml, line 64 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2iSAj2f8v2H2nh3FK:-MW3jG_v2xd4pLhoi2OZ:bie2nw3) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/pom.xml#L64)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I guess you meant 0.34.3? (it took me a while to figure this out)

Note that there's a jaeger.version property defined at the top level, but it is not used here, so the version is basically whatever is imported by Quarkus I would guess? that said, 0.34.3 is fairly old (a year old), and I wonder why Quarkus hasn't updated, and if there would be some issues if forcing a newer version (but it might not be possible sadly: https://github.com/quarkusio/quarkus/issues/5907)
</blockquote></details>

Yup, that's a sad thing.
___
*[perftest/gatling/pom.xml, line 119 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2hsY85tkEqcn4DNkI:-MW3jJDwAPGfpF2eRIY5:b-896fix) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/pom.xml#L119)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

let's move it under pluginManagement? (like it was done for jmeter?)
</blockquote></details>

Done.
___
*[perftest/gatling/README.md, line 6 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpkbnEDsC7J6RVoGzT:-MW3jMte5VjED4GNCYcE:bmk6yls) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/gatling/README.md#L6)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

I have a hard visualizing running a performance test with debugger attached and breakpoints tbh. If you investigate issues, it's probably faster to create a unit or integration test to reproduce some behavior observed and run it in a debugger, instead of having a whole performance + telemetry stack waiting while you're debugging?
</blockquote></details>

Our tests exercise with a TVS configured with `waitOnCollapse=true`, but the production setup is `waitOnCollapse=false`, which is a completely different thing. So once you hit such a situation, you can run the Nessie Server in your IDE and e.g. set a breakpoint to inspect the state. That is very helpful to know what is going on and test potential fixes in such a scenario. So I disagree that it's faster to create a unit test, because you don't always know what you have to fix and the unit-test-environment is also quite different esp. for TVS.
___
*[perftest/gatling/src/test/scala/Engine.scala, line 20 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2h-p71dYvrnwMD2IY:-MW3kDFED2B4ScnTC25X:b-bcfhfe) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/Engine.scala#L20)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is it important to keep how this class was generated?
</blockquote></details>

Sadly yes, to debug the simulation itself.
___
*[perftest/gatling/src/test/scala/IDEPathHelper.scala, line 19 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2gxjg9Fyw2SJoftT-:-MW3kIKH53LddpHDN3o2:b-bcfhfe) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/IDEPathHelper.scala#L19)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is it important to keep how this class was generated?
</blockquote></details>

Sadly yes, to debug the simulation itself.
___
*[perftest/gatling/src/test/scala/Recorder.scala, line 20 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2gpdv4lOUefzcQ2su:-MW3kK-i2EqnHMlqIonA:b-bcfhfe) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/Recorder.scala#L20)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

is it important to keep how this class was generated?
</blockquote></details>

Sadly yes, to debug the simulation itself.
___
*[perftest/measurement-pack/docker-compose.yml, line 84 at r2](https://reviewable.io/reviews/projectnessie/nessie/940#-MVpmr7O7ZsDai0W-GG9:-MW3kL_CCo87Pa6HXJZJ:b-kyol9s) ([raw file](https://github.com/projectnessie/nessie/blob/e0ee652c09703f0bcb6429d115e5781001018bc6/perftest/measurement-pack/docker-compose.yml#L84)):*
<details><summary><i>Previously, laurentgo (Laurent Goujon) wrote…</i></summary><blockquote>

Didn't we have those docker-compose.yml already, and they were removed instead of being adjusted for your changes?
</blockquote></details>

Moved this one to a separate file, updates to use the Nessie Docker image and updated the readme files.
___
*[perftest/measurement-pack/pom.xml, line 1 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2gM037bUayh5eHoNJ:-MW3kYfVAqTH-1bqRLDx:b-bwgnk6) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/measurement-pack/pom.xml#L1)) [...]

2021-03-18 12:56 UTC, rymurr commented
I think I have finally figured out why Ive been struggling w/ this PR: I think there is a mix of 'distributed' prod performance testing and local benchmarking. The addition of prometheus, grafana etc to do a localised benchmark on a jvm attached to a debugger is tripping me up. I had envisioned a prod-like environment (multiple nessies, real backend and the rest) that could be put in AWS, separate machines or whatever and a jmeter like application stress tests it in various ways. The proemtheus/graphana/jaeger stuff really exists to give observability into the distributed stress test. This is also aimed at users/evaluators and serves as one of several example prod setups.

My reading of this is its more like a benchmark. This is *very* useful for testing changes to core algorithms, for debugging issues under high load and as a (semi)regular part of our CI. the primary user is the Nessie developers. In which case I think the distributed observability tools and setup instructions for AWS are noisy. I see this as being akin to the [JMH based](https://github.com/apache/iceberg/tree/master/spark2/src/jmh/) tool the iceberg community uses to test algo changes.

So I am wondering: could we make a change to this PR to run it more like a JMH-style benchmark: in process, no docker etc? The grafana/prom stuff could change over to a more local report produced at the end of the run. Can then also integrate w/ a github action and build a regularly running benchmarking job to detect local perf anomalies quickly. This also gives all the flexibility we want in terms of server config, without necessarily needing to build a native image.

We can then re-tackle the distributed performance test when we know more about user modes and deployments. What do people think?

2021-03-18 16:31 UTC, laurentgo requested changes
> *[Reviewable](https://reviewable.io/reviews/projectnessie/nessie/940)* status: 18 of 33 files reviewed, 27 unresolved discussions (waiting on @laurentgo, @rymurr, and @snazy)

___
*[perftest/README.md, line 104 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2eDXBCj4v3ZQ6uRtf:-MW58zqs40w1lL0L4n9o:bc66fzb) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/README.md#L104)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

As long as we have just one simulation, yes. Other simulations that perform merges / transplants / GC probably end up in different classes.
</blockquote></details>

sure, but you could also create different plugin executions to be invoked like `mvn install gatling:test@commit-to-branch`?
___
*[perftest/gatling/src/test/scala/Engine.scala, line 20 at r3](https://reviewable.io/reviews/projectnessie/nessie/940#-MW2h-p71dYvrnwMD2IY:-MW5AAAl35C86wA4059j:b-4a534v) ([raw file](https://github.com/projectnessie/nessie/blob/60a366e2e630447f8d467a7299487b6cf9913fe6/perftest/gatling/src/test/scala/Engine.scala#L20)):*
<details><summary><i>Previously, snazy (Robert Stupp) wrote…</i></summary><blockquote>

Sadly yes, to debug the simulation itself.
</blockquote></details>

how the javadoc impacts the debugging?


<!-- Sent from Reviewable.io -->

2021-06-17 10:25 UTC, snazy commented
NOTE: All the Docker and "measurement-pack" has been moved to a separate branch, so this PR "only" contains the code to use Gatling and GH workflow infra code to collect the Gatling simulation-logs as GH WF-run artifacts and a new follow-up GH WF to generate the report HTML+YAML files, make these publicly accessible and link the HTML report as a commit status.

2021-06-17 10:25 UTC, snazy commented
Please ignore the two "REMOVE ME" commits.

2021-06-17 10:26 UTC, snazy commented
Still need to setup a new GH repo `nessie-ci` as the repo to hold the report HTML+YAML files. This is currently collected in https://github.com/snazy/some-test

2021-06-17 11:24 UTC, rymurr reviewed
This looks good to me. the only question i have is why the boilerplate from teh archetype? What is it used by and why do we need it.

2021-06-17 11:29 UTC, snazy commented
> This looks good to me. the only question i have is why the boilerplate from teh archetype? What is it used by and why do we need it.

Ah, that one's just to please IDEs - so you can run the simulation in a debugger or so.

2021-06-17 12:58 UTC, rymurr approved these changes

2021-06-17 14:36 UTC, merged